# Generated by Django 6.0.3 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_service_priceoverridelog_pricingrule'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services offered at this branch', related_name='branches', to='jobs.service'),
        ),
    ]
