# Generated by Django 6.0.3 on 2026-03-14 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_branch_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default=datetime.time(19, 30), help_text='Branch closing time — default 19:30'),
        ),
        migrations.AddField(
            model_name='branch',
            name='getfund_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GetFund levy rate — 0.00 until registered, then 2.50', max_digits=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='nhil_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NHIL levy rate — 0.00 until registered, then 2.50', max_digits=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Branch opening time — default 08:00'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vat_number',
            field=models.CharField(blank=True, help_text='GRA VAT registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT rate — 0.00 until registered, then 15.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='Flip to True when branch is GRA VAT registered'),
        ),
    ]
