# Generated by Django 6.0.3 on 2026-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Branch latitude — used for weather forecasting', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Branch longitude — used for weather forecasting', max_digits=9, null=True),
        ),
    ]
