from django.db import models


class DailyRiskFlag(models.Model):
    """
    A single risk signal detected for a daily sheet.
    Created by daily_risk_engine during EOD analysis.

    One DailyRiskReport has many DailyRiskFlags — one per detected anomaly.
    The description field is human-readable and must stand alone.
    """

    # ── Flag type constants ───────────────────────────────────
    CASH_VARIANCE          = 'CASH_VARIANCE'
    PAYMENT_METHOD_SHIFT   = 'PAYMENT_METHOD_SHIFT'
    POST_CLOSING_JOB       = 'POST_CLOSING_JOB'
    FLOAT_NOT_ACKNOWLEDGED = 'FLOAT_NOT_ACKNOWLEDGED'
    FLOAT_NOT_SIGNED_OFF   = 'FLOAT_NOT_SIGNED_OFF'
    PAYMENT_OUTSIDE_SHIFT  = 'PAYMENT_OUTSIDE_SHIFT'
    HIGH_SINGLE_PAYMENT    = 'HIGH_SINGLE_PAYMENT'
    DUPLICATE_AMOUNT       = 'DUPLICATE_AMOUNT'
    SHORT_SESSION          = 'SHORT_SESSION'
    CRITICAL_ACTION_SWITCH = 'CRITICAL_ACTION_SWITCH'
    NO_FLOAT_SET           = 'NO_FLOAT_SET'
    CARRY_FORWARD_HIGH     = 'CARRY_FORWARD_HIGH'

    FLAG_TYPE_CHOICES = [
        (CASH_VARIANCE,          'Cash Variance'),
        (PAYMENT_METHOD_SHIFT,   'Unusual Payment Method Distribution'),
        (POST_CLOSING_JOB,       'Job Created After Sheet Close'),
        (FLOAT_NOT_ACKNOWLEDGED, 'Float Not Acknowledged at Shift Start'),
        (FLOAT_NOT_SIGNED_OFF,   'Float Not Signed Off at Shift End'),
        (PAYMENT_OUTSIDE_SHIFT,  'Payment Confirmed Outside Shift Hours'),
        (HIGH_SINGLE_PAYMENT,    'Unusually High Single Payment'),
        (DUPLICATE_AMOUNT,       'Duplicate Payment Amount in Same Session'),
        (SHORT_SESSION,          'Abnormally Short Session Duration'),
        (CRITICAL_ACTION_SWITCH, 'Tab Switch During Critical Action'),
        (NO_FLOAT_SET,           'No Float Set for Cashier'),
        (CARRY_FORWARD_HIGH,     'High Carry-Forward Balance'),
    ]

    # ── Severity constants ────────────────────────────────────
    LOW      = 'LOW'
    MEDIUM   = 'MEDIUM'
    HIGH     = 'HIGH'
    CRITICAL = 'CRITICAL'

    SEVERITY_CHOICES = [
        (LOW,      'Low'),
        (MEDIUM,   'Medium'),
        (HIGH,     'High'),
        (CRITICAL, 'Critical'),
    ]

    # ── Scoring weights ───────────────────────────────────────
    # Used by DailyRiskReport to compute overall risk_score
    SEVERITY_WEIGHTS = {
        LOW     : 3,
        MEDIUM  : 10,
        HIGH    : 20,
        CRITICAL: 40,
    }

    report    = models.ForeignKey(
        'analytics.DailyRiskReport',
        on_delete    = models.CASCADE,
        related_name = 'flags',
    )
    flag_type = models.CharField(max_length=30, choices=FLAG_TYPE_CHOICES, db_index=True)
    severity  = models.CharField(max_length=10, choices=SEVERITY_CHOICES, db_index=True)

    description = models.TextField(
        help_text = (
            'Human-readable explanation. Must stand alone. '
            'Example: "Cash variance of GHS 45.00 detected. '
            'Expected GHS 1,250.00 (opening float GHS 100.00 + '
            'cash collected GHS 1,150.00), counted GHS 1,205.00."'
        ),
    )

    metadata = models.JSONField(
        default   = dict,
        help_text = 'Raw numbers that produced this flag for programmatic use.',
    )

    class Meta:
        ordering            = ['-severity', 'flag_type']
        verbose_name        = 'Daily Risk Flag'
        verbose_name_plural = 'Daily Risk Flags'

    def __str__(self):
        return f"[{self.severity}] {self.flag_type} — {self.report}"

    @property
    def weight(self):
        return self.SEVERITY_WEIGHTS.get(self.severity, 0)


class DailyRiskReport(models.Model):
    """
    Compiled risk assessment for a single daily sheet.
    One record per DailySalesSheet.

    Generated by Celery task (analytics.tasks.daily) after sheet closes.
    Trigger: post_save signal on DailySalesSheet when status → CLOSED.

    Risk score is a weighted sum of flag severities, capped at 100:
      CRITICAL = +40, HIGH = +20, MEDIUM = +10, LOW = +3

    Routing:
      score >= 70 or any CRITICAL flag → RM notified immediately
      score >= 40                       → RM notified at EOD summary
      score < 40                        → logged, surfaced in monthly review
    """

    daily_sheet = models.OneToOneField(
        'finance.DailySalesSheet',
        on_delete    = models.CASCADE,
        related_name = 'risk_report',
    )
    branch = models.ForeignKey(
        'organization.Branch',
        on_delete    = models.CASCADE,
        related_name = 'daily_risk_reports',
    )
    date = models.DateField(db_index=True)

    # ── Risk score ────────────────────────────────────────────
    risk_score = models.PositiveSmallIntegerField(
        default   = 0,
        help_text = '0–100 weighted sum of flag severities. Capped at 100.',
    )

    # ── Flag counts by severity ───────────────────────────────
    flag_count_critical = models.PositiveSmallIntegerField(default=0)
    flag_count_high     = models.PositiveSmallIntegerField(default=0)
    flag_count_medium   = models.PositiveSmallIntegerField(default=0)
    flag_count_low      = models.PositiveSmallIntegerField(default=0)

    # ── Generation metadata ───────────────────────────────────
    generated_at = models.DateTimeField()

    # ── RM review ─────────────────────────────────────────────
    requires_rm_review = models.BooleanField(
        default   = False,
        db_index  = True,
        help_text = 'True if risk_score >= 40 or any CRITICAL flag exists.',
    )
    rm_reviewed_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.SET_NULL,
        null         = True,
        blank        = True,
        related_name = 'rm_daily_reviews',
    )
    rm_reviewed_at = models.DateTimeField(null=True, blank=True)
    rm_notes       = models.TextField(blank=True)

    class Meta:
        ordering            = ['-date', '-risk_score']
        indexes             = [
            models.Index(fields=['branch', 'date']),
            models.Index(fields=['risk_score']),
            models.Index(fields=['requires_rm_review', 'date']),
        ]
        verbose_name        = 'Daily Risk Report'
        verbose_name_plural = 'Daily Risk Reports'

    def __str__(self):
        return f"{self.branch.code} | {self.date} | score={self.risk_score}"

    def compute_score(self):
        """
        Recompute risk_score and flag counts from related DailyRiskFlags.
        Call this after all flags have been created.
        """
        flags = self.flags.all()

        self.flag_count_critical = flags.filter(severity=DailyRiskFlag.CRITICAL).count()
        self.flag_count_high     = flags.filter(severity=DailyRiskFlag.HIGH).count()
        self.flag_count_medium   = flags.filter(severity=DailyRiskFlag.MEDIUM).count()
        self.flag_count_low      = flags.filter(severity=DailyRiskFlag.LOW).count()

        raw_score = (
            self.flag_count_critical * DailyRiskFlag.SEVERITY_WEIGHTS[DailyRiskFlag.CRITICAL] +
            self.flag_count_high     * DailyRiskFlag.SEVERITY_WEIGHTS[DailyRiskFlag.HIGH]     +
            self.flag_count_medium   * DailyRiskFlag.SEVERITY_WEIGHTS[DailyRiskFlag.MEDIUM]   +
            self.flag_count_low      * DailyRiskFlag.SEVERITY_WEIGHTS[DailyRiskFlag.LOW]
        )

        self.risk_score        = min(raw_score, 100)
        self.requires_rm_review = (
            self.risk_score >= 40 or
            self.flag_count_critical > 0
        )

        self.save(update_fields=[
            'risk_score',
            'flag_count_critical',
            'flag_count_high',
            'flag_count_medium',
            'flag_count_low',
            'requires_rm_review',
        ])

    @property
    def risk_level(self):
        if self.risk_score >= 70 or self.flag_count_critical > 0:
            return 'CRITICAL'
        if self.risk_score >= 40:
            return 'HIGH'
        if self.risk_score >= 20:
            return 'MEDIUM'
        return 'LOW'

    @property
    def total_flags(self):
        return (
            self.flag_count_critical +
            self.flag_count_high     +
            self.flag_count_medium   +
            self.flag_count_low
        )