from django.db import models


class WeeklyRiskFlag(models.Model):
    """
    A single risk signal detected at the weekly level.
    Created by weekly_risk_engine on Saturday night.

    Weekly flags are higher-level patterns that emerge across
    multiple days — not detectable on a single day's data.
    """

    # ── Flag type constants ───────────────────────────────────
    REVENUE_ANOMALY      = 'REVENUE_ANOMALY'
    HIGH_CASH_PROPORTION = 'HIGH_CASH_PROPORTION'
    COMPLETION_RATE_DROP = 'COMPLETION_RATE_DROP'
    DAILY_OUTLIER        = 'DAILY_OUTLIER'
    CARRY_FORWARD_HIGH   = 'CARRY_FORWARD_HIGH'
    REVENUE_VS_PRIOR     = 'REVENUE_VS_PRIOR'
    MULTIPLE_HIGH_RISK   = 'MULTIPLE_HIGH_RISK'
    SESSION_PATTERN      = 'SESSION_PATTERN'

    FLAG_TYPE_CHOICES = [
        (REVENUE_ANOMALY,      'Revenue Anomaly vs Rolling Average'),
        (HIGH_CASH_PROPORTION, 'Cash > 80% of Weekly Revenue'),
        (COMPLETION_RATE_DROP, 'Completion Rate Below Branch Average'),
        (DAILY_OUTLIER,        'Single Day > 3 Standard Deviations from Mean'),
        (CARRY_FORWARD_HIGH,   'High Carry-Forward Balance'),
        (REVENUE_VS_PRIOR,     'Revenue Variance vs Same Week Last Month'),
        (MULTIPLE_HIGH_RISK,   'Multiple High-Risk Days in One Week'),
        (SESSION_PATTERN,      'Abnormal Session Patterns Across Week'),
    ]

    # ── Severity constants ────────────────────────────────────
    LOW      = 'LOW'
    MEDIUM   = 'MEDIUM'
    HIGH     = 'HIGH'
    CRITICAL = 'CRITICAL'

    SEVERITY_CHOICES = [
        (LOW,      'Low'),
        (MEDIUM,   'Medium'),
        (HIGH,     'High'),
        (CRITICAL, 'Critical'),
    ]

    SEVERITY_WEIGHTS = {
        LOW     : 3,
        MEDIUM  : 10,
        HIGH    : 20,
        CRITICAL: 40,
    }

    report    = models.ForeignKey(
        'analytics.WeeklyRiskScore',
        on_delete    = models.CASCADE,
        related_name = 'flags',
    )
    flag_type   = models.CharField(max_length=30, choices=FLAG_TYPE_CHOICES, db_index=True)
    severity    = models.CharField(max_length=10, choices=SEVERITY_CHOICES, db_index=True)
    description = models.TextField()
    metadata    = models.JSONField(default=dict)

    class Meta:
        ordering            = ['-severity', 'flag_type']
        verbose_name        = 'Weekly Risk Flag'
        verbose_name_plural = 'Weekly Risk Flags'

    def __str__(self):
        return f"[{self.severity}] {self.flag_type} — {self.report}"

    @property
    def weight(self):
        return self.SEVERITY_WEIGHTS.get(self.severity, 0)


class WeeklyRiskScore(models.Model):
    """
    Compiled risk score for a weekly filing.
    One record per WeeklyReport.

    Generated by Celery task (analytics.tasks.weekly) after
    filing is submitted on Saturday night.

    Score algorithm:
    - Weighted average of daily risk scores
    - CRITICAL days weighted 3x
    - HIGH days weighted 2x
    - Plus penalty for week-level flags

    Finance spot-check threshold: score >= 50 or any CRITICAL flag.

    Finance assignment:
    - Requires review → system assigns to Finance reviewer
      (round-robin across active Finance users)
    - Finance reviewer clears or flags before RM can endorse monthly close
    """

    weekly_report = models.OneToOneField(
        'finance.WeeklyReport',
        on_delete    = models.CASCADE,
        related_name = 'risk_score',
    )
    branch = models.ForeignKey(
        'organization.Branch',
        on_delete    = models.CASCADE,
        related_name = 'weekly_risk_scores',
    )
    week_number = models.PositiveSmallIntegerField()
    year        = models.PositiveSmallIntegerField()

    # ── Risk scoring ──────────────────────────────────────────
    risk_score          = models.PositiveSmallIntegerField(
        default   = 0,
        help_text = '0–100. Weighted average of daily scores + week-level flags.',
    )
    highest_daily_risk  = models.PositiveSmallIntegerField(default=0)
    average_daily_risk  = models.PositiveSmallIntegerField(default=0)
    critical_days_count = models.PositiveSmallIntegerField(default=0)
    high_days_count     = models.PositiveSmallIntegerField(default=0)

    # ── Finance spot-check ────────────────────────────────────
    requires_finance_review = models.BooleanField(
        default   = False,
        db_index  = True,
        help_text = 'True if risk_score >= 50 or any CRITICAL flag.',
    )
    finance_reviewer = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.SET_NULL,
        null         = True,
        blank        = True,
        related_name = 'weekly_finance_reviews',
        help_text    = 'Assigned Finance reviewer (HQ level).',
    )
    finance_assigned_at = models.DateTimeField(null=True, blank=True)
    finance_reviewed_at = models.DateTimeField(null=True, blank=True)

    PENDING = 'PENDING'
    CLEARED = 'CLEARED'
    FLAGGED = 'FLAGGED'

    FINANCE_STATUS_CHOICES = [
        (PENDING, 'Pending Review'),
        (CLEARED, 'Cleared by Finance'),
        (FLAGGED, 'Flagged — Needs Attention'),
    ]

    finance_status = models.CharField(
        max_length = 10,
        choices    = FINANCE_STATUS_CHOICES,
        default    = PENDING,
        db_index   = True,
    )
    finance_notes  = models.TextField(blank=True)

    # ── Generation metadata ───────────────────────────────────
    generated_at = models.DateTimeField()

    class Meta:
        ordering            = ['-year', '-week_number', '-risk_score']
        indexes             = [
            models.Index(fields=['branch', 'year', 'week_number']),
            models.Index(fields=['risk_score']),
            models.Index(fields=['requires_finance_review', 'finance_status']),
        ]
        verbose_name        = 'Weekly Risk Score'
        verbose_name_plural = 'Weekly Risk Scores'

    def __str__(self):
        return (
            f"{self.branch.code} | W{self.week_number}/{self.year} "
            f"| score={self.risk_score} | {self.finance_status}"
        )

    @property
    def risk_level(self):
        if self.risk_score >= 70:
            return 'CRITICAL'
        if self.risk_score >= 50:
            return 'HIGH'
        if self.risk_score >= 30:
            return 'MEDIUM'
        return 'LOW'