# Generated by Django 6.0.3 on 2026-08-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0026_alter_job_intake_channel'),
        ('organization', '0004_add_branch_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('PRINT', 'Printing'), ('LAMINATE', 'Laminating'), ('BIND', 'Binding'), ('CUT', 'Cutting'), ('FINISH', 'Hand finishing')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order work flows through. Printing comes before laminating, which comes before binding. Used to walk a job through the stations its services require.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['sequence'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('DIGITAL_PRESS', 'Digital press'), ('LARGE_FORMAT', 'Large format printer'), ('LAMINATOR', 'Laminator'), ('BINDER', 'Binding machine'), ('CUTTER', 'Cutter'), ('PLOTTER', 'Plotter')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('max_paper_size', models.CharField(blank=True, help_text='Largest sheet this class of device handles, e.g. A3. Blank where size is not the limit — a laminator and a press are constrained by different things.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(help_text='The station a device of this type works at.', on_delete=django.db.models.deletion.PROTECT, related_name='machine_types', to='production.station')),
            ],
            options={
                'verbose_name': 'Machine Type',
                'verbose_name_plural': 'Machine Types',
                'ordering': ['station__sequence', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='What the branch calls it, e.g. "Canon C5535i".', max_length=80)),
                ('model_number', models.CharField(blank=True, help_text='Manufacturer model, e.g. "imageRUNNER ADVANCE DX C5535i".', max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text='Owned and in service. False once sold or written off.')),
                ('is_available', models.BooleanField(default=True, help_text='Running right now. False takes the machine out of scheduling and halts what is queued on it.')),
                ('unavailable_reason', models.CharField(blank=True, help_text='Why it is down, for whoever asks before it is fixed.', max_length=200)),
                ('unavailable_since', models.DateTimeField(blank=True, null=True)),
                ('commissioned_on', models.DateField(blank=True, help_text='When it entered service. Useful once age and downtime correlate.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='organization.branch')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='production.machinetype')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['branch', 'machine_type__station__sequence', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'is_active', 'is_available'], name='machine_branch_state_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Order within this service. Print before bind.')),
                ('setup_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Fixed cost per job — plate, settings, loading stock.', max_digits=6)),
                ('minutes_per_unit', models.DecimalField(decimal_places=4, default=0, help_text='Marginal cost per unit once running.', max_digits=8)),
                ('machine_type', models.ForeignKey(blank=True, help_text='The class of device this step needs. Null where the work is done by hand — a branch with no such machine cannot take the job, and RoutingEngine sends it somewhere that can.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_routes', to='production.machinetype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_routes', to='jobs.service')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_routes', to='production.station')),
            ],
            options={
                'verbose_name': 'Service Station',
                'verbose_name_plural': 'Service Stations',
                'ordering': ['service', 'sequence'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('service', 'station'), name='unique_service_station')],
            },
        ),
        migrations.CreateModel(
            name='StationTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour_of_day', models.PositiveSmallIntegerField(help_text='0–23, local time. A busy afternoon is not a quiet morning.')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0 = Monday through 5 = Saturday. The week runs Mon–Sat.')),
                ('observed_minutes_per_unit', models.DecimalField(decimal_places=4, help_text='Rolling average of what this station actually achieves here.', max_digits=8)),
                ('correction_factor', models.DecimalField(decimal_places=3, default=1, help_text='Measured over predicted. Absorbs everything the model does not represent — machine contention, hand finishing, breaks, interruptions — without pretending to model any of it. Above one means the branch runs slower here than the seed figure.', max_digits=6)),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Observations behind these figures. Low counts should not be quoted to a customer — a number the branch cannot hit is worse than no number.')),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_timings', to='organization.branch')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='production.station')),
            ],
            options={
                'verbose_name': 'Station Timing',
                'verbose_name_plural': 'Station Timings',
                'ordering': ['branch', 'station', 'day_of_week', 'hour_of_day'],
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'station'], name='timing_branch_station_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'station', 'day_of_week', 'hour_of_day'), name='unique_station_timing_slot')],
            },
        ),
    ]
