# Generated by Django 6.0.3 on 2026-10-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='max_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Widest material this class of device takes, in millimetres. Large format is measured by roll width rather than sheet size, and routing compares a job against it — a banner wider than the machine cannot be printed on it at all.', null=True),
        ),
    ]
