# Generated by Django 6.0.3 on 2026-10-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_add_branch_coordinates'),
        ('production', '0002_machinetype_max_width_mm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people', models.PositiveSmallIntegerField(default=1, help_text='How many jobs this branch can work at this station at once. Usually the number of trained people, not machines — a second printer with nobody to run it adds no capacity.')),
                ('notes', models.TextField(blank=True, help_text='Why it is this number, so the next person to change it knows.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_capacity', to='organization.branch')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_capacity', to='production.station')),
            ],
            options={
                'ordering': ['branch__code', 'station__sequence'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'station'), name='one_capacity_row_per_branch_station')],
            },
        ),
    ]
