# Generated by Django 6.0.3 on 2026-10-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_machinetype_max_width_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='max_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Widest material this machine takes, in millimetres. It belongs to the machine rather than its class: a 6ft and a 10ft roll printer are both large format, and a route that had to name each width separately would rule out machines that could do the work perfectly well.', null=True),
        ),
    ]
