# Generated by Django 6.0.3 on 2026-03-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('tier', models.CharField(choices=[('REGULAR', 'Regular'), ('PREFERRED', 'Preferred'), ('VIP', 'VIP')], default='REGULAR', max_length=20)),
                ('is_priority', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='organization.branch')),
            ],
            options={
                'ordering': ['-visit_count', 'first_name'],
            },
        ),
    ]
