# Generated by Django 6.0.3 on 2026-03-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this customer was first recorded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_walkin',
            field=models.BooleanField(default=False, help_text='True if auto-created from a walk-in receipt delivery'),
        ),
    ]
