# Generated by Django 6.0.3 on 2026-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_branch_customerprofile_is_walkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address of customer or organisation'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company, school, or church name if applicable', max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='confidence_score',
            field=models.PositiveIntegerField(default=0, help_text='System-computed score 0–100 based on job volume, payment consistency, profile completeness, and tenure. Score ≥ 50 triggers a credit eligibility recommendation.'),
        ),
    ]
