# Generated by Django 6.0.3 on 2026-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerprofile_address_customerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business'), ('INSTITUTION', 'Institution')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='institution_subtype',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'School'), ('CHURCH', 'Church / Religious'), ('NGO', 'NGO / Non-profit'), ('GOVT', 'Government / Public'), ('OTHER', 'Other Institution')], help_text='Only applicable when customer_type is INSTITUTION', max_length=20),
        ),
    ]
