# Generated by Django 6.0.3 on 2026-04-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customereditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='affiliation',
            field=models.ForeignKey(blank=True, help_text='Institution or business this individual is affiliated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_individuals', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='affiliation_active',
            field=models.BooleanField(default=True, help_text='Set to False if individual has left the affiliated organisation'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Optional — used for birthday messages', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER_NOT', 'Prefer not to say')], max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('CALL', 'Call'), ('SMS', 'SMS'), ('EMAIL', 'Email')], help_text='How this customer prefers to be contacted', max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text='Alternative number — searchable but not used for payments or automated messages', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('MS', 'Ms'), ('MADAM', 'Madam'), ('DR', 'Dr'), ('PROF', 'Prof'), ('REV', 'Rev'), ('ESQ', 'Esq'), ('OTHER', 'Other')], help_text='Honorific title e.g. Mr, Dr, Prof', max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='title_other',
            field=models.CharField(blank=True, help_text='Custom title when title=OTHER', max_length=50),
        ),
    ]
