# Generated by Django 6.0.3 on 2026-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerprofile_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='total_spend',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lifetime spend across all completed jobs. Auto-updated on job completion.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
