# Generated by Django 6.0.3 on 2026-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Job-redeemable credit balance, capped at GHS 200. Reconciled from CustomerWalletTransaction — never edited directly.', max_digits=6),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='wallet_last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last wallet add or redemption. Drives 6-month expiry; resets on any activity.', null=True),
        ),
    ]
