# Generated by Django 6.0.3 on 2026-03-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
