# Generated by Django 6.0.3 on 2026-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='download_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='download_pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
