# Generated by Django 6.0.3 on 2026-04-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_pendingactivation_conflict_new_region'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='belt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_accounts', to='organization.belt'),
        ),
    ]
