# Generated by Django 6.0.3 on 2026-04-24 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_belt'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('PAYROLL', 'Payroll'), ('PROCUREMENT', 'Procurement & Vendors'), ('BUDGET', 'Budget & Envelopes'), ('REVIEWS', 'Monthly Close Reviews'), ('REPORTING', 'Analytics & Reporting')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Domain',
                'verbose_name_plural': 'Staff Domains',
                'ordering': ['user', 'domain'],
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
