# Generated by Django 6.0.3 on 2026-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_business_owner',
            field=models.BooleanField(default=False, help_text='True only for the business owner/CEO. Gates sensitive features like investor statement generation. Deliberately separate from is_staff/is_superuser which are Django admin flags.'),
        ),
    ]
