# Generated by Django 6.0.3 on 2026-04-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0016_add_sheet_number'),
        ('inventory', '0002_branchequipment_maintenancelog'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_FINANCE', 'Pending Finance Approval'), ('FINANCE_APPROVED', 'Finance Approved'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered – Awaiting BM Acceptance'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('order_number', models.CharField(help_text='e.g. REP-WLB-2026-W15', max_length=30, unique=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, help_text='Total estimated cost of all line items.', max_digits=12)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget approved by Finance. May differ from estimate.', max_digits=12, null=True)),
                ('finance_notes', models.TextField(blank=True)),
                ('submitted_to_finance_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ops_notes', models.TextField(blank=True)),
                ('bm_notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_acceptances', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_approvals', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_orders', to='organization.branch')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_dispatches', to=settings.AUTH_USER_MODEL)),
                ('submitted_to_finance_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_submissions', to=settings.AUTH_USER_MODEL)),
                ('weekly_report', models.OneToOneField(help_text='The locked EOW report this order was generated from.', on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_order', to='finance.weeklyreport')),
            ],
            options={
                'verbose_name': 'Replenishment Order',
                'verbose_name_plural': 'Replenishment Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_qty', models.DecimalField(decimal_places=2, help_text='Quantity derived from EOW consumption.', max_digits=10)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity approved by Finance. Defaults to requested if not set.', max_digits=10, null=True)),
                ('delivered_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity delivered by Operations.', max_digits=10, null=True)),
                ('accepted_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity confirmed received by BM.', max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost per unit at time of order generation.', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='requested_qty × unit_cost', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_lines', to='inventory.consumableitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.replenishmentorder')),
            ],
            options={
                'verbose_name': 'Replenishment Line Item',
                'verbose_name_plural': 'Replenishment Line Items',
                'ordering': ['consumable__category', 'consumable__name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_qty', models.DecimalField(decimal_places=2, help_text='What Operations claimed to deliver.', max_digits=10)),
                ('accepted_qty', models.DecimalField(decimal_places=2, help_text='What BM confirmed receiving.', max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, help_text='delivered_qty - accepted_qty. Positive = short delivery.', max_digits=10)),
                ('bm_reason', models.TextField(help_text='BM explanation of the discrepancy.')),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending Investigation'), ('RESOLVED', 'Resolved'), ('WRITTEN_OFF', 'Written Off')], db_index=True, default='PENDING', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='procurement.replenishmentlineitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='procurement.replenishmentorder')),
            ],
            options={
                'verbose_name': 'Delivery Discrepancy',
                'verbose_name_plural': 'Delivery Discrepancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Stock'), ('EXCESS', 'Excess / Overstock'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='DAMAGED', max_length=10)),
                ('reason_notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns_collected', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by_bm', models.ForeignKey(blank=True, help_text='BM who confirmed the return at point of collection.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns_confirmed', to=settings.AUTH_USER_MODEL)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns', to='inventory.consumableitem')),
                ('order', models.ForeignKey(help_text='The delivery order on which this return was collected.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns', to='procurement.replenishmentorder')),
            ],
            options={
                'verbose_name': 'Stock Return',
                'verbose_name_plural': 'Stock Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='replenishmentorder',
            index=models.Index(fields=['branch', 'status'], name='procurement_branch__6640f8_idx'),
        ),
        migrations.AddIndex(
            model_name='replenishmentorder',
            index=models.Index(fields=['status', 'created_at'], name='procurement_status_b056f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='replenishmentlineitem',
            unique_together={('order', 'consumable')},
        ),
    ]
