# Generated by Django 6.0.3 on 2026-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishmentorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed – Ready for Dispatch'), ('PENDING_FINANCE', 'Pending Finance Approval'), ('FINANCE_APPROVED', 'Finance Approved'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered – Awaiting BM Acceptance'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
