# Generated by Django 6.0.3 on 2026-04-23 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_deliveryunit'),
        ('procurement', '0002_alter_replenishmentorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('payment_term', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MOMO', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Owner Approval'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets_proposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annual Budget',
                'verbose_name_plural': 'Annual Budgets',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('BI_YEARLY', 'Bi-Yearly'), ('QUARTERLY', 'Quarterly')], max_length=10)),
                ('period', models.CharField(choices=[('ANNUAL', 'Full Year'), ('H1', 'H1 (Jan–Jun)'), ('H2', 'H2 (Jul–Dec)'), ('Q1', 'Q1 (Jan–Mar)'), ('Q2', 'Q2 (Apr–Jun)'), ('Q3', 'Q3 (Jul–Sep)'), ('Q4', 'Q4 (Oct–Dec)')], max_length=10)),
                ('category', models.CharField(choices=[('STOCK', 'Stock & Materials'), ('PAYROLL', 'Payroll'), ('MAINTENANCE', 'Maintenance'), ('MARKETING', 'Marketing'), ('INVESTMENT', 'Investment'), ('UTILITIES', 'Utilities'), ('EQUIPMENT', 'Equipment'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('ceiling', models.DecimalField(decimal_places=2, default=0, help_text='Proposed ceiling amount for this envelope.', max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount approved by Owner.', max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, help_text='Amount spent to date — auto-updated on procurement clearance.', max_digits=12)),
                ('carry_forward', models.DecimalField(decimal_places=2, default=0, help_text='Unspent balance carried forward from previous period.', max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='procurement.annualbudget')),
            ],
            options={
                'verbose_name': 'Budget Envelope',
                'verbose_name_plural': 'Budget Envelopes',
                'ordering': ['budget__year', 'period_type', 'category'],
                'unique_together': {('budget', 'period', 'category')},
            },
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current unit price from latest verified invoice.', max_digits=10)),
                ('price_history', models.JSONField(blank=True, default=list, help_text='List of {date, price, reference} dicts — oldest first.')),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred vendor for this consumable.')),
                ('variance_threshold', models.DecimalField(decimal_places=2, default=10, help_text='Alert Finance if new price deviates by more than this % from current.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_items', to='inventory.consumableitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Item',
                'verbose_name_plural': 'Vendor Items',
                'ordering': ['vendor__name', 'consumable__name'],
                'unique_together': {('vendor', 'consumable')},
            },
        ),
    ]
