# Generated by Django 6.0.3 on 2026-04-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_vendor_annualbudget_budgetenvelope_vendoritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentorder',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MOMO', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='disbursement_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt',
            field=models.FileField(blank=True, help_text='Uploaded by Operations after purchase. Closes the loop.', null=True, upload_to='procurement/receipts/'),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_receipt_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt_variance_flagged',
            field=models.BooleanField(default=False, help_text='True if receipt amount differs from approved budget by >5%.'),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replenishmentorder',
            name='receipt_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_receipt_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
