# Generated by Django 6.0.3 on 2026-03-09 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('job_type', models.CharField(choices=[('INSTANT', 'Instant'), ('PRODUCTION', 'Production'), ('DESIGN', 'Design')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('BRIEFED', 'Briefed'), ('DESIGN_IN_PROGRESS', 'Design In Progress'), ('SAMPLE_SENT', 'Sample Sent'), ('REVISION_REQUESTED', 'Revision Requested'), ('DESIGN_APPROVED', 'Design Approved'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_PAYMENT', 'Ready for Payment'), ('PAID', 'Paid'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('intake_channel', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], default='WALK_IN', max_length=20)),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_routed', models.BooleanField(default=False)),
                ('routing_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Executing branch if routed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_jobs', to='organization.branch')),
                ('branch', models.ForeignKey(help_text='Originating branch — owns the customer relationship', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='organization.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='customers.customerprofile')),
                ('intake_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='jobs/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('ORIGINAL', 'Original File'), ('SAMPLE', 'Design Sample'), ('FINAL', 'Final File'), ('REFERENCE', 'Reference')], default='ORIGINAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jobs.job')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
