# Generated by Django 6.0.3 on 2026-03-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('INSTANT', 'Instant'), ('PRODUCTION', 'Production'), ('DESIGN', 'Design')], max_length=20)),
                ('unit', models.CharField(choices=[('PER_PAGE', 'Per Page'), ('PER_COPY', 'Per Copy'), ('PER_SQM', 'Per Square Metre'), ('PER_PIECE', 'Per Piece'), ('PER_SET', 'Per Set'), ('FLAT_RATE', 'Flat Rate')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('requires_design', models.BooleanField(default=False)),
                ('requires_file_upload', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overridden_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_overrides', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_overrides', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for color jobs e.g. 1.5 means color costs 1.5x base price', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for company-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='organization.branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='jobs.service')),
            ],
            options={
                'ordering': ['service', 'branch'],
                'unique_together': {('service', 'branch')},
            },
        ),
    ]
