# Generated by Django 6.0.3 on 2026-03-14 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('jobs', '0004_fsm_redesign'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='job',
            name='cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='10% of full job value — applied when cancelled after IN_PROGRESS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='daily_sheet',
            field=models.ForeignKey(blank=True, help_text='The daily sheet this job belongs to — set on creation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='finance.dailysalessheet'),
        ),
        migrations.AddField(
            model_name='job',
            name='momo_reference',
            field=models.CharField(blank=True, help_text='MoMo transaction reference — mandatory for MoMo payments', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('POS', 'POS'), ('CREDIT', 'Credit Account')], default='', help_text='Set by cashier at payment confirmation', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='pos_approval_code',
            field=models.CharField(blank=True, help_text='POS terminal approval code — mandatory for POS payments', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Mandatory explanation if job is voided — BM authorised only'),
        ),
        migrations.AddField(
            model_name='job',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid by customer — set by cashier on confirmation', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided'), ('HALTED', 'Halted'), ('SAMPLE_SENT', 'Sample Sent'), ('REVISION_REQUESTED', 'Revision Requested'), ('DESIGN_APPROVED', 'Design Approved'), ('BRIEFED', 'Briefed (Deprecated)'), ('DESIGN_IN_PROGRESS', 'Design In Progress (Deprecated)'), ('QUEUED', 'Queued (Deprecated)'), ('READY_FOR_PAYMENT', 'Ready for Payment (Deprecated)')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='requires_file_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='spec_template',
            field=models.JSONField(blank=True, default=list, help_text='Field definitions for the dynamic intake form. See model docstring.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('PER_COPY', 'Per Copy'), ('PER_PIECE', 'Per Piece'), ('PER_SQFT', 'Per Sq Ft'), ('PER_SQCM', 'Per Sq Cm'), ('PER_JOB', 'Per Job')], default='PER_PIECE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proforma_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('sequence', models.PositiveIntegerField(editable=False, help_text='Auto-incremented sequence per branch per year')),
                ('issued_to', models.CharField(help_text='Organisation or individual name', max_length=150)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person at the organisation', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(help_text='7 days from issue date — system enforced')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CONVERTED', 'Converted to Job'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10)),
                ('line_items', models.JSONField(default=list, help_text='List of dicts: [{service_id, service_name, quantity, unit_price, total}, ...]')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 until branch is GRA registered', max_digits=10)),
                ('nhil_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('getfund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('converted_at', models.DateTimeField(blank=True, help_text='Timestamp when customer paid and job was created', null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='organization.branch')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proformas_converted', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas_issued', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, help_text='Populated when proforma converts to a real job', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoice', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='proforma',
            field=models.ForeignKey(blank=True, help_text='Proforma invoice this job was created from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_jobs', to='jobs.proformainvoice'),
        ),
    ]
