# Generated by Django 6.0.3 on 2026-03-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_service_options_job_cancellation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='pricing_tiers',
            field=models.JSONField(blank=True, help_text='Optional tiered pricing. If set, overrides base_price calculation. Use price_per_unit for per-unit tiers (Typing), flat_price for flat-fee tiers (Binding).', null=True),
        ),
    ]
