# Generated by Django 6.0.3 on 2026-03-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_pricingrule_pricing_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('is_color', models.BooleanField(default=False)),
                ('paper_size', models.CharField(blank=True, default='A4', max_length=10)),
                ('sides', models.CharField(choices=[('SINGLE', 'Single-sided'), ('DOUBLE', 'Double-sided')], default='SINGLE', max_length=10)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('file_source', models.CharField(choices=[('HARDCOPY', 'Walk-in Hardcopy'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('USB', 'USB Storage'), ('TYPING', 'Typing Request'), ('NA', 'Not Applicable')], default='NA', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit at time of recording', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='unit_price × quantity (or as calculated by PricingEngine)', max_digits=10)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Sort order within the job — lower = shown first')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='jobs.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='jobs.service')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
