# Generated by Django 6.0.3 on 2026-03-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_job_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='smart_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Pre-filled defaults for POS modal. Derived from service name.'),
        ),
    ]
