# Generated by Django 6.0.3 on 2026-03-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_service_smart_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='carried_forward',
            field=models.BooleanField(default=False, help_text='True if this job was unpaid at sheet close and carried to next day.'),
        ),
    ]
