# Generated by Django 6.0.3 on 2026-03-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_add_job_carried_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, help_text='Set when a draft expires or is manually discarded.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='draft_expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-set to created_at + 3 days for DRAFT jobs. Null for all other statuses.', null=True),
        ),
    ]
