# Generated by Django 6.0.3 on 2026-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_draft_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cash_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of cash given by customer', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change returned to customer', max_digits=10, null=True),
        ),
    ]
