# Generated by Django 6.0.3 on 2026-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_cash_tendered_change_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service thumbnail image', null=True, upload_to='services/'),
        ),
    ]
