# Generated by Django 6.0.3 on 2026-03-23 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_add_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_closing',
            field=models.BooleanField(default=False, help_text='True if job was created after branch closing time — BM only.'),
        ),
        migrations.AddField(
            model_name='job',
            name='post_closing_approved_by',
            field=models.ForeignKey(blank=True, help_text='BM who approved this post-closing job.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_closing_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='post_closing_reason',
            field=models.TextField(blank=True, help_text='Mandatory reason for post-closing job — entered by BM.'),
        ),
    ]
