# Generated by Django 6.0.3 on 2026-03-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_creditaccount_recommended_by_and_more'),
        ('jobs', '0013_add_post_closing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='credit_account',
            field=models.ForeignKey(blank=True, help_text='Credit account used if payment method is CREDIT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='finance.creditaccount'),
        ),
    ]
