# Generated by Django 6.0.3 on 2026-03-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_dailysalessheet_total_credit_settled_and_more'),
        ('jobs', '0014_job_credit_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='partial_credit_account',
            field=models.ForeignKey(blank=True, help_text='Credit account charged for the unpaid portion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partial_credit_jobs', to='finance.creditaccount'),
        ),
        migrations.AddField(
            model_name='job',
            name='partial_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount added to credit account for partial credit payments.', max_digits=10, null=True),
        ),
    ]
