# Generated by Django 6.0.3 on 2026-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_partial_credit_account_job_partial_credit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided'), ('HALTED', 'Halted'), ('INTAKE_HELD', 'Intake Held'), ('SAMPLE_SENT', 'Sample Sent'), ('REVISION_REQUESTED', 'Revision Requested'), ('DESIGN_APPROVED', 'Design Approved'), ('BRIEFED', 'Briefed (Deprecated)'), ('DESIGN_IN_PROGRESS', 'Design In Progress (Deprecated)'), ('QUEUED', 'Queued (Deprecated)'), ('READY_FOR_PAYMENT', 'Ready for Payment (Deprecated)')], default='DRAFT', max_length=30),
        ),
    ]
