# Generated by Django 6.0.3 on 2026-07-04 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_add_job_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='handover_disputed',
            field=models.BooleanField(default=False, help_text='True if the cashier reported not receiving cash from the BM for this job.'),
        ),
        migrations.AddField(
            model_name='job',
            name='handover_disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='handover_disputed_by',
            field=models.ForeignKey(blank=True, help_text='Cashier who raised the dispute.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='handover_resolved_at',
            field=models.DateTimeField(blank=True, help_text='Set when the cashier affirms receipt (with or without a prior dispute).', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='handover_resolved_by',
            field=models.ForeignKey(blank=True, help_text='Cashier who confirmed the handover.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_resolutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
