# Generated by Django 6.0.3 on 2026-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_handover_disputed_job_handover_disputed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('POS', 'POS'), ('CREDIT', 'Credit Account'), ('WALLET', 'Wallet Credit')], default='', help_text='Set by cashier at payment confirmation', max_length=10),
        ),
    ]
