# Generated by Django 6.0.3 on 2026-08-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_job_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='handed_over_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='handed_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_handed_over', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='handover_state',
            field=models.CharField(choices=[('AWAITING_COLLECTION', 'Awaiting collection'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('HANDED_OVER', 'Handed over')], db_index=True, default='AWAITING_COLLECTION', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_state',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('DEPOSIT_PAID', 'Deposit paid'), ('SETTLED', 'Settled')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='work_state',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PRODUCTION', 'In production'), ('FINISHING', 'Finishing'), ('QUALITY_CHECK', 'Quality check'), ('DONE', 'Done')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='JobHalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('MACHINE_BREAKDOWN', 'Machine breakdown'), ('MATERIALS_OUT', 'Materials unavailable'), ('CUSTOMER_PAUSE', 'Customer requested pause'), ('AWAITING_CUSTOMER', 'Awaiting customer decision'), ('QUALITY_FAILURE', 'Quality failure'), ('OTHER', 'Other')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('work_state_at_halt', models.CharField(max_length=20)),
                ('halted_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('halted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_halts_raised', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halts', to='jobs.job')),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_halts_resumed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Halt',
                'verbose_name_plural': 'Job Halts',
                'ordering': ['-halted_at'],
                'indexes': [models.Index(fields=['job', 'resumed_at'], name='halt_job_resumed_idx')],
            },
        ),
    ]
