# Generated by Django 6.0.3 on 2026-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_backfill_lifecycle_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatuslog',
            name='axis',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('WORK', 'Work'), ('HANDOVER', 'Handover'), ('RECORD', 'Record')], db_index=True, default='RECORD', help_text='Which lifecycle axis this transition moved. RECORD covers draft/intake-held/cancellation, which are facts about the record rather than any axis, and is also what every pre-rebuild log row is backfilled to.', max_length=10),
        ),
    ]
