# Generated by Django 6.0.3 on 2026-08-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customerprofile_wallet_balance_and_more'),
        ('jobs', '0022_jobstatuslog_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='agreed_terms',
            field=models.CharField(blank=True, help_text='What the customer agreed to at acceptance — a deposit percentage, or CREDIT. The cashier still executes it; this records what was agreed when the quote was accepted.', max_length=20),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, help_text='Last follow-up reminder sent to the issuing manager', null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='supersedes',
            field=models.OneToOneField(blank=True, help_text='The earlier version this revision replaces', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='jobs.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='issued_to',
            field=models.CharField(help_text='Name as printed on the quote. Snapshotted at issue — the customer record may change later, and the quote must show what was actually sent.', max_length=150),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CONVERTED', 'Converted to Job'), ('SUPERSEDED', 'Superseded by a revision'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='valid_until',
            field=models.DateField(help_text='21 days from issue — system enforced, and reset on each revision. Expiry is terminal: an expired quote is replaced by a new one at current prices, never revived.'),
        ),
    ]
