# Generated by Django 6.0.3 on 2026-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_proformainvoice_agreed_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CONVERTED', 'Converted to Job'), ('SUPERSEDED', 'Superseded by a revision'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
