# Generated by Django 6.0.3 on 2026-08-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_proformainvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='intake_channel',
            field=models.CharField(choices=[('WALK_IN', 'Walk-in'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('QUOTE', 'Accepted quote')], default='WALK_IN', max_length=20),
        ),
    ]
