# Generated by Django 6.0.3 on 2026-08-17 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_job_intake_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('PASSED', 'Cleared for production'), ('ARTWORK_PROBLEM', 'Artwork not usable'), ('SPEC_UNCLEAR', 'Specification unclear'), ('SPEC_IMPOSSIBLE', 'Cannot be made as ordered'), ('WRONG_FILE', 'Wrong or missing file'), ('OTHER', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='What was found. Optional on a pass, since there is usually nothing to say; a mandatory note becomes ritual.')),
                ('customer_contacted', models.BooleanField(default=False, help_text='Whether the customer was called or messaged about this.')),
                ('customer_response', models.TextField(blank=True, help_text='What the customer said, in the words of whoever spoke to them.')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_verifications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Verification',
                'verbose_name_plural': 'Job Verifications',
                'ordering': ['-checked_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['job', 'outcome'], name='verification_job_outcome_idx')],
            },
        ),
    ]
