# Generated by Django 6.0.3 on 2026-08-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_jobverification'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhalt',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halts_caused', to='production.machine'),
        ),
    ]
