# Generated by Django 6.0.3 on 2026-08-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_jobhalt_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfile',
            name='colour_mode',
            field=models.CharField(blank=True, help_text='As declared by the file — RGB, CMYK, Grayscale.', max_length=20),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='dpi',
            field=models.PositiveIntegerField(blank=True, help_text='Lower of horizontal and vertical, as the weaker axis is what prints badly.', null=True),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='height_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='metadata_state',
            field=models.CharField(choices=[('PENDING', 'Not yet read'), ('MEASURED', 'Measured'), ('UNSUPPORTED', 'Format not readable'), ('FAILED', 'Could not be read')], default='PENDING', help_text='Distinguishes a file never read from one read without result.', max_length=20),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='width_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
