# Generated by Django 6.0.3 on 2026-09-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_jobfile_colour_mode_jobfile_content_type_jobfile_dpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Floor price for one piece, applied before quantity. Large-format work costs the same in file prep, cutting and packing whatever its size, so a small piece cannot be sold at its area price. 0 means no floor.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('POS', 'POS'), ('CREDIT', 'Credit Account'), ('WALLET', 'Wallet Credit'), ('ONLINE', 'Online Payment')], default='', help_text='Set by cashier at payment confirmation', max_length=10),
        ),
    ]
