# Generated by Django 6.0.3 on 2026-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_pricingrule_minimum_price_alter_job_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfile',
            name='pdf_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
