# Generated by Django 6.0.3 on 2026-10-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_jobfile_pdf_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, help_text='When the floor said this would be done, frozen at the moment it was promised. Not recomputed: the question worth answering later is whether the promise was kept, and a figure that moves with the queue can never be wrong.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_started_at',
            field=models.DateTimeField(blank=True, help_text='When someone actually began. An estimate missed because the job sat in a queue for a day is a different failure from one missed because the work took longer than thought, and without this the two cannot be told apart.', null=True),
        ),
    ]
