# Generated by Django 6.0.3 on 2026-06-27 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note PIN',
                'verbose_name_plural': 'Note PINs',
            },
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('amber', 'Amber'), ('blue', 'Blue'), ('green', 'Green'), ('violet', 'Violet'), ('rose', 'Rose'), ('slate', 'Slate')], default='amber', max_length=10)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Note',
                'verbose_name_plural': 'Personal Notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
