# Generated by Django 6.0.3 on 2026-06-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='note_type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('TASK', 'Task')], default='NOTE', max_length=10),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False, help_text='True for the last checkpoint before the due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='personal_notes.personalnote')),
            ],
            options={
                'verbose_name': 'Task Checkpoint',
                'verbose_name_plural': 'Task Checkpoints',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['note', 'scheduled_at'], name='personal_no_note_id_6e3085_idx')],
            },
        ),
    ]
