# Generated by Django 6.0.3 on 2026-03-17 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierfloat',
            name='cover_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='covering_for',
            field=models.ForeignKey(blank=True, help_text='The cashier whose shift this person is covering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floats_covered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='overtime_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='overtime_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='shift_notes',
            field=models.TextField(blank=True, help_text='Cashier notes on incidents or observations during shift'),
        ),
    ]
