# Generated by Django 6.0.3 on 2026-03-20 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_invoicelineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_downloads', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_logs', to='finance.dailysalessheet')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
