# Generated by Django 6.0.3 on 2026-03-21 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_sheetdownloadlog'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(help_text='ISO week number (1–52)')),
                ('year', models.PositiveIntegerField()),
                ('date_from', models.DateField(help_text='Monday of the week')),
                ('date_to', models.DateField(help_text='Saturday of the week')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked')], default='DRAFT', max_length=12)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_momo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_petty_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit_issued', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_cash_in_till', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_jobs_created', models.PositiveIntegerField(default=0)),
                ('total_jobs_complete', models.PositiveIntegerField(default=0)),
                ('total_jobs_cancelled', models.PositiveIntegerField(default=0)),
                ('carry_forward_count', models.PositiveIntegerField(default=0, help_text='Jobs still pending payment at week end')),
                ('inventory_snapshot', models.JSONField(blank=True, default=dict, help_text='Populated by inventory app — consumables used this week')),
                ('bm_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to='organization.branch')),
                ('daily_sheets', models.ManyToManyField(blank=True, related_name='weekly_reports', to='finance.dailysalessheet')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-year', '-week_number'],
                'unique_together': {('branch', 'week_number', 'year')},
            },
        ),
    ]
