# Generated by Django 6.0.3 on 2026-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or sender name — shown on receipt when provided', max_length=150),
        ),
    ]
