# Generated by Django 6.0.3 on 2026-03-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_receipt_company_name'),
        ('jobs', '0011_add_cash_tendered_change_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('POS', 'POS')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('momo_reference', models.CharField(blank=True, max_length=20)),
                ('pos_approval_code', models.CharField(blank=True, max_length=50)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='1 for first leg, 2 for second leg')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_legs', to='jobs.job')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_legs', to='finance.receipt')),
            ],
            options={
                'verbose_name': 'Payment Leg',
                'verbose_name_plural': 'Payment Legs',
                'ordering': ['job', 'sequence'],
            },
        ),
    ]
