# Generated by Django 6.0.3 on 2026-03-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierfloat',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date this float is scheduled for — set when pre-created at EOD', null=True),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='daily_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_floats', to='finance.dailysalessheet'),
        ),
    ]
