# Generated by Django 6.0.3 on 2026-03-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_cashierfloat_scheduled_date_and_more'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditaccount',
            name='recommended_by',
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='nominated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='nominated_by',
            field=models.ForeignKey(blank=True, help_text='Branch Manager who nominated this account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts_nominated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Belt Manager who approved this account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
