# Generated by Django 6.0.3 on 2026-03-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_creditaccount_recommended_by_and_more'),
        ('jobs', '0014_job_credit_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalessheet',
            name='total_credit_settled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('JOB_PAYMENT', 'Job Payment'), ('CREDIT_SETTLEMENT', 'Credit Settlement')], default='JOB_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='jobs.job'),
        ),
    ]
