# Generated by Django 6.0.3 on 2026-03-30 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_dailysalessheet_total_credit_settled_and_more'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField(help_text='Month number 1–12')),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted — Awaiting Endorsement'), ('ENDORSED', 'Endorsed & Finalized'), ('REJECTED', 'Rejected — Resubmission Required')], default='OPEN', max_length=12)),
                ('summary_snapshot', models.JSONField(blank=True, default=dict, help_text='Full month summary frozen at submission time')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bm_notes', models.TextField(blank=True)),
                ('endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('belt_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to='organization.branch')),
                ('endorsed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes_endorsed', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Close',
                'verbose_name_plural': 'Monthly Closes',
                'ordering': ['-year', '-month'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
    ]
