# Generated by Django 6.0.3 on 2026-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_cashierfloat_acknowledgement_denominations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierfloat',
            name='closing_denomination_breakdown',
            field=models.JSONField(blank=True, help_text='Denomination count at EOD cash count — same structure as opening_denomination_breakdown', null=True),
        ),
    ]
