# Generated by Django 6.0.3 on 2026-04-03 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_cashierfloat_closing_denomination_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashierfloat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='handover_acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='BM who acknowledged receipt of handover float', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floats_handover_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='handover_at',
            field=models.DateTimeField(blank=True, help_text='When cashier handed float to BM', null=True),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='handover_denomination_breakdown',
            field=models.JSONField(blank=True, help_text='Denomination count at mid-day handover', null=True),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='handover_float',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Physical float amount counted and handed to BM at mid-day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='is_handover',
            field=models.BooleanField(default=False, help_text='True if this shift ended mid-day with a handover to next cashier'),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='next_float',
            field=models.OneToOneField(blank=True, help_text='The next cashier float record this carries into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_float', to='finance.cashierfloat'),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='shift_sequence',
            field=models.PositiveSmallIntegerField(default=1, help_text='Order of this cashier shift within the day. 1 = first cashier, 2 = second cashier after handover, etc.'),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='closing_cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Physical cash counted at shift end by cashier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='closing_denomination_breakdown',
            field=models.JSONField(blank=True, help_text='Denomination count at EOD cash count', null=True),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='daily_sheet',
            field=models.ForeignKey(blank=True, help_text='Null when staged — linked when sheet opens', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_floats', to='finance.dailysalessheet'),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed: opening float + cash collected - petty cash', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='opening_denomination_breakdown',
            field=models.JSONField(blank=True, help_text='Denomination count at float receipt. e.g. {"1":0,"2":0,"5":2,"10":0,"20":2,"50":0,"100":0,"200":0}', null=True),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='opening_float',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Physical cash handed to cashier at shift start', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashierfloat',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date this float is scheduled for — set when pre-staged at EOD', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cashierfloat',
            unique_together={('daily_sheet', 'cashier', 'shift_sequence')},
        ),
        migrations.AddIndex(
            model_name='cashierfloat',
            index=models.Index(fields=['daily_sheet', 'cashier'], name='finance_cas_daily_s_7ebaeb_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierfloat',
            index=models.Index(fields=['scheduled_date', 'cashier'], name='finance_cas_schedul_0b361c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierfloat',
            index=models.Index(fields=['is_signed_off'], name='finance_cas_is_sign_6f1fed_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierfloat',
            index=models.Index(fields=['morning_acknowledged'], name='finance_cas_morning_bc57df_idx'),
        ),
    ]
