# Generated by Django 6.0.3 on 2026-04-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_cashierfloat_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyclose',
            name='belt_notes',
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='clarification_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='clarification_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='clarification_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='finance_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='finance_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='finance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='finance_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes_reviewing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='pdf_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='pdf_downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes_pdf_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyclose',
            name='rm_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monthlyclose',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted — Awaiting Finance Review'), ('FINANCE_REVIEWING', 'Finance Reviewing'), ('NEEDS_CLARIFICATION', 'Needs Clarification'), ('RESUBMITTED', 'Resubmitted — Finance Re-reviewing'), ('FINANCE_CLEARED', 'Finance Cleared — Awaiting RM Endorsement'), ('ENDORSED', 'Endorsed by RM'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
    ]
