# Generated by Django 6.0.3 on 2026-04-07 09:08

from django.db import migrations, models


def backfill_sheet_numbers(apps, schema_editor):
    DailySalesSheet = apps.get_model('finance', 'DailySalesSheet')

    branch_ids = DailySalesSheet.objects.values_list(
        'branch_id', flat=True
    ).distinct()

    for branch_id in branch_ids:
        sheets = DailySalesSheet.objects.filter(
            branch_id=branch_id
        ).order_by('date', 'id')

        branch_code = sheets.first().branch.code if sheets.exists() else 'UNK'

        for seq, sheet in enumerate(sheets, start=1):
            month = sheet.date.strftime('%m')
            day   = sheet.date.strftime('%d')
            sheet.sheet_number = f"{branch_code}-{month}{day}-{seq:03d}"
            sheet.save(update_fields=['sheet_number'])


def reverse_backfill(apps, schema_editor):
    DailySalesSheet = apps.get_model('finance', 'DailySalesSheet')
    DailySalesSheet.objects.all().update(sheet_number='')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_monthlyclose_full_status_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalessheet',
            name='sheet_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_sheet_numbers, reverse_backfill),
    ]