# Generated by Django 6.0.3 on 2026-05-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_add_sheet_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashierfloat',
            name='is_overtime',
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='physical_confirm_disputed',
            field=models.BooleanField(default=False, help_text='True if cashier reported not receiving float on an auto-closed sheet'),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='physical_confirm_disputed_at',
            field=models.DateTimeField(blank=True, help_text='When the dispute was raised', null=True),
        ),
    ]
