# Generated by Django 6.0.3 on 2026-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_add_float_dispute_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierfloat',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
    ]
