# Generated by Django 6.0.3 on 2026-06-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_add_cashierfloat_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cashierfloat',
            name='finance_cas_daily_s_7ebaeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashierfloat',
            name='finance_cas_schedul_0b361c_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashierfloat',
            name='finance_cas_is_sign_6f1fed_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashierfloat',
            name='finance_cas_morning_bc57df_idx',
        ),
    ]
