# Generated by Django 6.0.3 on 2026-06-30 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_add_hourly_sheet_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierfloat',
            name='is_recovery_float',
            field=models.BooleanField(default=False, help_text='True if this float was auto-created by the system recovery task because no float existed by 4pm. Indicates a disrupted or delayed start day — not a normal BM-staged float.'),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_evidence',
            field=models.TextField(blank=True, help_text='URL, ECG reference, news link, or other provable evidence'),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_reason',
            field=models.CharField(blank=True, choices=[('POWER_OUTAGE', 'Power Outage'), ('FLOODING', 'Flooding'), ('SECURITY_INCIDENT', 'Security Incident'), ('FORCE_MAJEURE', 'Force Majeure'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disruptions_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_status',
            field=models.CharField(blank=True, choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='disruption_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disruptions_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
