# Generated by Django 6.0.3 on 2026-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_add_disruption_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='total_jobs_registered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='total_jobs_walkin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
