# Generated by Django 6.0.3 on 2026-07-06 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_add_weekly_customer_mix'),
        ('organization', '0004_add_branch_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('name', models.CharField(help_text='e.g. "Independence Day (observed)"', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_holidays', to='organization.branch')),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays_declared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['branch', 'date'], name='holiday_branch_date_idx')],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
