# Generated by Django 6.0.3 on 2026-07-08 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_enable_pg_trgm'),
        ('finance', '0024_publicholiday'),
        ('jobs', '0018_job_handover_disputed_job_handover_disputed_at_and_more'),
        ('organization', '0004_add_branch_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT_ADDED', 'Credit Added'), ('REDEEMED_JOB', 'Redeemed Against Job'), ('EXPIRED', 'Expired')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=8)),
                ('consent_confirmed_at', models.DateTimeField(blank=True, help_text='Set only for CREDIT_ADDED — timestamp of explicit customer consent captured by the cashier.', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='organization.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='customers.customerprofile')),
                ('job', models.ForeignKey(blank=True, help_text='Null only for EXPIRED entries — every CREDIT_ADDED and REDEEMED_JOB entry must tie to a real job.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='jobs.job')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Wallet Transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='finance_cus_custome_cf105c_idx'), models.Index(fields=['branch', 'transaction_type'], name='finance_cus_branch__5d5832_idx')],
            },
        ),
    ]
