# Generated by Django 6.0.3 on 2026-07-08 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_customerwallettransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallettransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Null only for EXPIRED entries — system-triggered, no human actor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
