# Generated by Django 6.0.3 on 2026-08-01 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_customerwallettransaction_recorded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierfloat',
            name='is_recovery_entry',
            field=models.BooleanField(default=False, help_text='True if this sign-off was recorded retrospectively during a stranded sheet recovery, rather than by the cashier at end of shift.'),
        ),
        migrations.AddField(
            model_name='cashierfloat',
            name='reconciled_with',
            field=models.ForeignKey(blank=True, help_text='The cashier who physically counted and confirmed the cash. Recorded separately from signed_off_by so a recovery entry can never read as a manager unilaterally deciding the till figure.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floats_reconciled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='recovered_by',
            field=models.ForeignKey(blank=True, help_text='Who keyed the recovery entry — not necessarily who counted the cash', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheets_recovered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='recovery_notes',
            field=models.TextField(blank=True, help_text='Mandatory explanation recorded at recovery'),
        ),
        migrations.AddField(
            model_name='dailysalessheet',
            name='recovery_reason',
            field=models.CharField(blank=True, choices=[('POWER_OUTAGE', 'Power outage'), ('SYSTEM_DOWN', 'System unavailable'), ('NETWORK_FAILURE', 'Network failure'), ('NOT_CLOSED', 'Not closed at end of day'), ('OTHER', 'Other')], help_text='Why this sheet could not be closed on its own day', max_length=20),
        ),
    ]
