# Generated by Django 6.0.3 on 2026-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_cashierfloat_is_recovery_entry_and_more'),
        ('organization', '0004_add_branch_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ['-year', '-week_number', '-date_from'], 'verbose_name': 'Weekly Report', 'verbose_name_plural': 'Weekly Reports'},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The month this report belongs to. A week split by a month boundary is filed twice — once in each month — so the month is what tells the two apart.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('branch', 'week_number', 'year', 'month')},
        ),
    ]
