# Generated by Django 6.0.3 on 2026-09-02 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_backfill_weekly_report_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySheetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('REVIEW', 'Reviewed by the manager'), ('QUERY', 'Asked by Finance'), ('RESPONSE', 'Answered by the manager')], default='REVIEW', max_length=10)),
                ('body', models.TextField(help_text="Why this day is the way it is, in the writer's own words.")),
                ('flagged_for', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_notes', to=settings.AUTH_USER_MODEL)),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_notes', to='finance.dailysalessheet')),
            ],
            options={
                'verbose_name': 'Day Sheet Note',
                'verbose_name_plural': 'Day Sheet Notes',
                'ordering': ['created_at'],
            },
        ),
    ]
