# Generated by Django 6.0.3 on 2026-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_daysheetnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalessheet',
            name='total_online',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Paid through Print Octos — earned by the branch, never in its till', max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='total_online',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Paid through Print Octos — earned by the branch, never in its till', max_digits=12),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('POS', 'POS'), ('CREDIT', 'Credit Account'), ('ONLINE', 'Paid Online')], max_length=10),
        ),
    ]
