# Generated by Django 6.0.3 on 2026-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_dailysalessheet_total_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalessheet',
            name='total_payment_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What the payment provider took. total_online is the gross, so the day still reconciles against the bank.', max_digits=12),
        ),
    ]
