# Generated by Django 6.0.3 on 2026-03-09 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('jobs', '0003_jobstatuslog'),
        ('organization', '0002_branch_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='OPEN', max_length=20)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='organization.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='customers.customerprofile')),
                ('jobs', models.ManyToManyField(blank=True, related_name='conversations', to='jobs.job')),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('branch', 'contact_phone', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SYSTEM', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio'), ('NOTE', 'Internal Note')], default='TEXT', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='communications/media/%Y/%m/')),
                ('external_id', models.CharField(blank=True, help_text='WhatsApp message ID, Twilio SID etc.', max_length=255)),
                ('call_duration', models.PositiveIntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('caller_id', models.CharField(blank=True, max_length=20)),
                ('is_internal_note', models.BooleanField(default=False, help_text='Internal notes are visible to staff only, never sent to customer')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, help_text='Staff member who sent this. Null for inbound messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
