from django.db import models
from apps.core.models import AuditModel


class PayrollRecord(AuditModel):
    """
    A single payroll entry for an employee for a given period.
    Generated by the payroll engine based on pay_frequency.
    """

    # Status
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    PAID = 'PAID'
    CANCELLED = 'CANCELLED'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (PAID, 'Paid'),
        (CANCELLED, 'Cancelled'),
    ]

    # Payment Method
    BANK = 'BANK'
    MOBILE_MONEY = 'MOBILE_MONEY'
    CASH = 'CASH'

    PAYMENT_METHOD_CHOICES = [
        (BANK, 'Bank Transfer'),
        (MOBILE_MONEY, 'Mobile Money'),
        (CASH, 'Cash'),
    ]

    employee = models.ForeignKey(
        'hr.Employee',
        on_delete=models.PROTECT,
        related_name='payroll_records'
    )
    period_start = models.DateField()
    period_end = models.DateField()
    base_salary = models.DecimalField(max_digits=10, decimal_places=2)
    bonus = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deductions = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    net_pay = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PENDING)
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENT_METHOD_CHOICES,
        default=BANK
    )
    payment_reference = models.CharField(max_length=100, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    approved_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='approved_payrolls'
    )
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['-period_end']
        unique_together = [['employee', 'period_start', 'period_end']]

    def __str__(self):
        return (
            f"{self.employee.employee_number} | "
            f"{self.period_start} → {self.period_end} | "
            f"GHS {self.net_pay} | {self.status}"
        )

    def save(self, *args, **kwargs):
        # Auto-calculate net pay
        self.net_pay = self.base_salary + self.bonus - self.deductions
        super().save(*args, **kwargs)