# Generated by Django 6.0.3 on 2026-03-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0011_add_cash_tendered_change_given'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
            ],
            options={
                'verbose_name': 'Consumable Category',
                'verbose_name_plural': 'Consumable Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('paper_size', models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('N/A', 'Not Applicable')], default='N/A', help_text='Paper size — N/A for non-paper items', max_length=5)),
                ('unit_type', models.CharField(choices=[('SHEETS', 'Sheets'), ('UNITS', 'Units'), ('PERCENT', 'Percentage')], default='SHEETS', max_length=10)),
                ('unit_label', models.CharField(default='sheets', help_text='Human-readable unit label e.g. sheets, pcs, %', max_length=30)),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='Alert when stock falls to or below this level')),
                ('reorder_qty', models.PositiveIntegerField(default=0, help_text='Suggested reorder quantity')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.consumablecategory')),
            ],
            options={
                'verbose_name': 'Consumable Item',
                'verbose_name_plural': 'Consumable Items',
                'ordering': ['category', 'paper_size', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('IN', 'Stock Received'), ('OUT', 'Job Consumption'), ('WASTE', 'Waste / Spoilage'), ('CORRECTION', 'HQ Correction')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Always positive — direction determined by movement_type', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock level after this movement — snapshot for audit', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organization.branch')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.consumableitem')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_recorded', to=settings.AUTH_USER_MODEL)),
                ('reference_job', models.ForeignKey(blank=True, help_text='Job that triggered this movement (OUT only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of sheets/units wasted', max_digits=8)),
                ('reason', models.CharField(choices=[('JAM', 'Paper Jam'), ('MISPRINT', 'Misprint / Print Error'), ('DAMAGE', 'Physical Damage'), ('OTHER', 'Other')], default='JAM', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_incidents', to='organization.branch')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_incidents', to='inventory.consumableitem')),
                ('job', models.ForeignKey(blank=True, help_text='Job being worked on when waste occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_incidents', to='jobs.job')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.OneToOneField(blank=True, help_text='The WASTE StockMovement created for this incident', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_incident', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'Waste Incident',
                'verbose_name_plural': 'Waste Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, default=1.0, help_text='Consumable units used per 1 page/set/unit of service', max_digits=8)),
                ('applies_to_color', models.BooleanField(default=True, help_text='If False, only applies to B&W jobs')),
                ('applies_to_bw', models.BooleanField(default=True, help_text='If False, only applies to color jobs')),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_mappings', to='inventory.consumableitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_mappings', to='jobs.service')),
            ],
            options={
                'verbose_name': 'Service Consumable',
                'verbose_name_plural': 'Service Consumables',
                'unique_together': {('service', 'consumable')},
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Current stock level', max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='organization.branch')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stocks', to='inventory.consumableitem')),
                ('last_movement', models.ForeignKey(blank=True, help_text='Most recent movement that updated this stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'Branch Stock',
                'verbose_name_plural': 'Branch Stock Levels',
                'unique_together': {('branch', 'consumable')},
            },
        ),
    ]
