# Generated by Django 6.0.3 on 2026-03-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Equipment name e.g. Canon iR-ADV 5531i Printer', max_length=200)),
                ('asset_code', models.CharField(blank=True, help_text='Auto-generated unique asset tag e.g. WLB-EQP-0001', max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units of this equipment at the branch')),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('NEEDS_SERVICE', 'Needs Service'), ('OUT_OF_SERVICE', 'Out of Service')], default='GOOD', max_length=15)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number(s) — separate multiple with commas', max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, help_text='Date equipment was purchased', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in GHS', max_digits=10, null=True)),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiry date', null=True)),
                ('last_serviced', models.DateField(blank=True, help_text='Date of last service or maintenance', null=True)),
                ('next_service_due', models.DateField(blank=True, help_text='Scheduled next service date', null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location within branch e.g. Front Desk, Production Room', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = decommissioned / removed from branch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='organization.branch')),
            ],
            options={
                'verbose_name': 'Branch Equipment',
                'verbose_name_plural': 'Branch Equipment',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('ROUTINE', 'Routine Maintenance'), ('REPAIR', 'Repair'), ('REPLACEMENT', 'Part Replacement'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], default='ROUTINE', max_length=15)),
                ('service_date', models.DateField(help_text='Date the service or repair was performed')),
                ('description', models.TextField(help_text='What was done — be specific')),
                ('performed_by', models.CharField(help_text='Technician name or company who performed the work', max_length=150)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of service in GHS', max_digits=10, null=True)),
                ('parts_replaced', models.TextField(blank=True, help_text='List any parts that were replaced')),
                ('next_due', models.DateField(blank=True, help_text='Recommended date for next service', null=True)),
                ('condition_after', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('NEEDS_SERVICE', 'Needs Service'), ('OUT_OF_SERVICE', 'Out of Service')], help_text='Equipment condition after this service', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='inventory.branchequipment')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
