# Generated by Django 6.0.3 on 2026-04-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_branchequipment_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_size', models.DecimalField(decimal_places=2, help_text='Number of stock units per deliverable pack.', max_digits=10)),
                ('pack_label', models.CharField(help_text='Human-readable pack name e.g. box, ream, cartridge, unit.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional description e.g. "1 box = 2,500 sheets (5 reams)"')),
                ('is_active', models.BooleanField(default=True)),
                ('consumable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_unit', to='inventory.consumableitem')),
            ],
            options={
                'verbose_name': 'Delivery Unit',
                'verbose_name_plural': 'Delivery Units',
                'ordering': ['consumable__category', 'consumable__name'],
            },
        ),
    ]
