from django.db import models
from apps.core.models import AuditModel


class BranchTransferCredit(AuditModel):
    """
    Tracks inter-branch revenue attribution when a job is routed
    from one branch to another for production.

    Rule:
    - Origin branch collects the payment and owns the revenue
    - Destination branch produces the job and earns a production credit
    - Belt Manager reconciles transfer credits on a weekly/monthly cycle

    This model is the paper trail for that reconciliation.
    It is auto-created by the system when a routed job is paid —
    cashier never creates this manually.
    """

    class Status(models.TextChoices):
        PENDING      = 'PENDING',      'Pending Reconciliation'
        RECONCILED   = 'RECONCILED',   'Reconciled'

    job                 = models.OneToOneField(
        'jobs.Job',
        on_delete=models.PROTECT,
        related_name='transfer_credit',
    )
    origin_branch       = models.ForeignKey(
        'organization.Branch',
        on_delete=models.PROTECT,
        related_name='transfer_credits_sent',
        help_text='Branch that collected the payment',
    )
    destination_branch  = models.ForeignKey(
        'organization.Branch',
        on_delete=models.PROTECT,
        related_name='transfer_credits_received',
        help_text='Branch that produced the job',
    )

    # ── Value ─────────────────────────────────────────────────
    job_value           = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text='Full job value at time of payment',
    )
    amount_collected    = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text='Actual amount collected — may be deposit or full payment',
    )

    # ── Attribution ───────────────────────────────────────────
    origin_sheet        = models.ForeignKey(
        'finance.DailySalesSheet',
        on_delete=models.PROTECT,
        related_name='transfer_credits_originated',
        help_text='Daily sheet of the origin branch on payment day',
    )

    # ── Reconciliation ────────────────────────────────────────
    status              = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.PENDING,
    )
    reconciled_by       = models.ForeignKey(
        'accounts.CustomUser',
        on_delete=models.PROTECT,
        related_name='transfer_credits_reconciled',
        null=True,
        blank=True,
        help_text='Belt Manager who reconciled this transfer',
    )
    reconciled_at       = models.DateTimeField(null=True, blank=True)
    reconciliation_notes = models.TextField(blank=True)

    # ── Auto-fill reason ──────────────────────────────────────
    system_reason       = models.TextField(
        blank=True,
        help_text='Auto-generated by system describing the routing context',
    )

    class Meta:
        ordering        = ['-created_at']
        verbose_name        = 'Branch Transfer Credit'
        verbose_name_plural = 'Branch Transfer Credits'

    def __str__(self) -> str:
        return (
            f"{self.origin_branch.code} → "
            f"{self.destination_branch.code} — "
            f"GHS {self.job_value} — "
            f"{self.status}"
        )

    @property
    def is_reconciled(self) -> bool:
        return self.status == self.Status.RECONCILED