# Generated by Django 6.0.3 on 2026-03-17 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_jobposition_applicant_onboardingrecord_and_more'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr.employee')),
            ],
            options={
                'ordering': ['employee', 'day_of_week', 'start_time'],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted — Awaiting BM Approval'), ('REJECTED', 'Rejected by Peer'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined by Manager'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('bm_notes', models.TextField(blank=True)),
                ('initiator_date', models.DateField()),
                ('cover_date', models.DateField()),
                ('compensation_date', models.DateField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_accepted', to='hr.employee')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swaps_approved', to=settings.AUTH_USER_MODEL)),
                ('compensation_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_as_compensation', to='hr.employeeshift')),
                ('cover_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_as_cover', to='hr.employeeshift')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_initiated', to='hr.employee')),
                ('initiator_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_as_initiator', to='hr.employeeshift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('override_type', models.CharField(choices=[('SWAP', 'Swap'), ('OVERTIME', 'Overtime'), ('COVER', 'Cover'), ('ABSENCE', 'Absence')], max_length=20)),
                ('override_start', models.TimeField(blank=True, null=True)),
                ('override_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='hr.employee')),
                ('original_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='hr.employeeshift')),
                ('swap_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='hr.employeeshiftswap')),
            ],
            options={
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date', 'override_type')},
            },
        ),
    ]
