# Generated by Django 6.0.3 on 2026-03-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeeshift_employeeshiftswap_shiftoverride'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], default='FULL_DAY', max_length=12)),
                ('days', models.CharField(help_text='Comma-separated day integers e.g. "0,1,2,3,4" for Mon–Fri', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_shifts', to='organization.branch')),
            ],
            options={
                'verbose_name': 'Branch Shift',
                'verbose_name_plural': 'Branch Shifts',
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(choices=[('ATTENDANT', 'Attendant'), ('CASHIER', 'Cashier'), ('BRANCH_MANAGER', 'Branch Manager')], max_length=20)),
                ('job_lock_buffer', models.PositiveIntegerField(default=0, help_text='Minutes after shift end when job creation locks for this role')),
                ('signoff_buffer', models.PositiveIntegerField(default=0, help_text='Minutes after shift end when portal forces sign-off')),
                ('autoclose_buffer', models.PositiveIntegerField(blank=True, help_text='Minutes after shift end for auto-close (BM only — leave blank for others)', null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='hr.branchshift')),
            ],
            options={
                'verbose_name': 'Shift Role Config',
                'verbose_name_plural': 'Shift Role Configs',
                'ordering': ['shift', 'role_name'],
                'unique_together': {('shift', 'role_name')},
            },
        ),
    ]
