# Generated by Django 6.0.3 on 2026-04-13 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_region'),
        ('hr', '0004_add_branch_shift_role_config'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagequestionnaire',
            options={'ordering': ['role', 'stage', 'question_number']},
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stagequestionnaire',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='vacancies',
        ),
        migrations.RemoveField(
            model_name='onboardingrecord',
            name='appointment_letter_sent_at',
        ),
        migrations.RemoveField(
            model_name='onboardingrecord',
            name='dependants_details',
        ),
        migrations.RemoveField(
            model_name='onboardingrecord',
            name='has_dependants',
        ),
        migrations.RemoveField(
            model_name='onboardingrecord',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='onboardingrecord',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='stagescore',
            name='interview_date',
        ),
        migrations.AddField(
            model_name='applicant',
            name='appointed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicant',
            name='appointment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='branch_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applicants', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='branch_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_applicants', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='onboarding_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='onboarding_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferred_channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='role_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_applicants', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('SCREENING', 'Screening'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_DONE', 'Interview Done'), ('FINAL_REVIEW', 'Final Review'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('APPOINTED', 'Appointed'), ('AWAITING_ACCEPTANCE', 'Awaiting Acceptance'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('ONBOARDING', 'Onboarding'), ('INFORMATION_SUBMITTED', 'Information Submitted'), ('INFORMATION_VERIFIED', 'Information Verified'), ('OFFER_ISSUED', 'Offer Issued'), ('ACTIVE', 'Active')], default='RECEIVED', max_length=30),
        ),
        migrations.AddField(
            model_name='applicant',
            name='track',
            field=models.CharField(choices=[('WEBSITE', 'Public Website'), ('RECOMMENDATION', 'BM Recommendation'), ('APPOINTMENT', 'CEO Direct Appointment'), ('INTERNAL', 'Internal Transfer')], default='WEBSITE', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='hr.jobposition'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='positions_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='track',
            field=models.CharField(choices=[('PUBLIC', 'Public Application'), ('RECOMMENDATION', 'BM Recommendation'), ('APPOINTMENT', 'CEO Direct Appointment')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='ghana_card_scan',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_1_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_1_employer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_1_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_1_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_1_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_1_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_2_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_2_employer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_2_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_2_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_2_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='guarantor_2_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='reference_employer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='reference_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='reference_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='reference_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='reference_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='ssnit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_onboarding_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagequestionnaire',
            name='pass_threshold',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='stagequestionnaire',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_questions', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='stagescore',
            name='interview_conducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagescore',
            name='interview_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stagescore',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('FILLED', 'Filled')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingrecord',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted - Awaiting HR Review'), ('VERIFIED', 'Verified - Ready for Offer'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagequestionnaire',
            name='guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='stagequestionnaire',
            unique_together={('role', 'stage', 'question_number')},
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.CharField(default='FULL_TIME', max_length=20)),
                ('salary_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_frequency', models.CharField(default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('probation_months', models.PositiveSmallIntegerField(default=3)),
                ('additional_terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='recruitment/offer_letters/%Y/%m/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer_letter', to='hr.applicant')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_letters', to='organization.branch')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_offer_letters', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_letters', to='accounts.role')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='offer_expires_at',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='position',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='stage',
        ),
    ]
