# Generated by Django 6.0.3 on 2026-06-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_stagequestionnaire_options_and_more'),
        ('hr', '0005_shiftroleconfig_role_times'),
    ]

    operations = [
    ]
