from django.db import models
from apps.core.models import AuditModel


class ReplenishmentOrder(AuditModel):
    """
    One replenishment order per branch per week.

    Auto-generated from a branch's locked WeeklyReport.
    Flows through: DRAFT → PENDING_FINANCE → FINANCE_APPROVED
                   → IN_TRANSIT → DELIVERED → CLOSED

    A DRAFT is generated by the system on EOW submission.
    Operations submits to Finance. Finance approves budget.
    Operations executes delivery. BM accepts. Cycle closes.
    """

    class Status(models.TextChoices):
        DRAFT             = 'DRAFT',             'Draft'
        CONFIRMED         = 'CONFIRMED',         'Confirmed – Ready for Dispatch'
        PENDING_FINANCE   = 'PENDING_FINANCE',   'Pending Finance Approval'
        FINANCE_APPROVED  = 'FINANCE_APPROVED',  'Finance Approved'
        IN_TRANSIT        = 'IN_TRANSIT',        'In Transit'
        DELIVERED         = 'DELIVERED',         'Delivered – Awaiting BM Acceptance'
        CLOSED            = 'CLOSED',            'Closed'
        CANCELLED         = 'CANCELLED',         'Cancelled'

    branch = models.ForeignKey(
        'organization.Branch',
        on_delete    = models.PROTECT,
        related_name = 'replenishment_orders',
    )
    weekly_report = models.OneToOneField(
        'finance.WeeklyReport',
        on_delete    = models.PROTECT,
        related_name = 'replenishment_order',
        help_text    = 'The locked EOW report this order was generated from.',
    )
    status = models.CharField(
        max_length = 20,
        choices    = Status.choices,
        default    = Status.DRAFT,
        db_index   = True,
    )
    order_number = models.CharField(
        max_length = 30,
        unique     = True,
        help_text  = 'e.g. REP-WLB-2026-W15',
    )

    # Finance clearance
    estimated_total = models.DecimalField(
        max_digits     = 12,
        decimal_places = 2,
        default        = 0,
        help_text      = 'Total estimated cost of all line items.',
    )
    approved_budget = models.DecimalField(
        max_digits     = 12,
        decimal_places = 2,
        null           = True,
        blank          = True,
        help_text      = 'Budget approved by Finance. May differ from estimate.',
    )
    finance_notes = models.TextField(blank=True)

    # Actors
    submitted_to_finance_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.PROTECT,
        related_name = 'procurement_submissions',
        null         = True,
        blank        = True,
    )
    submitted_to_finance_at = models.DateTimeField(null=True, blank=True)

    approved_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.PROTECT,
        related_name = 'procurement_approvals',
        null         = True,
        blank        = True,
    )
    approved_at = models.DateTimeField(null=True, blank=True)

    dispatched_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.PROTECT,
        related_name = 'procurement_dispatches',
        null         = True,
        blank        = True,
    )
    dispatched_at = models.DateTimeField(null=True, blank=True)

    accepted_by = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.PROTECT,
        related_name = 'procurement_acceptances',
        null         = True,
        blank        = True,
    )
    accepted_at = models.DateTimeField(null=True, blank=True)

    ops_notes = models.TextField(blank=True)
    bm_notes  = models.TextField(blank=True)

    # Receipt verification
    receipt             = models.FileField(
        upload_to  = 'procurement/receipts/',
        null       = True,
        blank      = True,
        help_text  = 'Uploaded by Operations after purchase. Closes the loop.',
    )
    receipt_uploaded_at  = models.DateTimeField(null=True, blank=True)
    receipt_uploaded_by  = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.PROTECT,
        related_name = 'procurement_receipt_uploads',
        null         = True,
        blank        = True,
    )
    receipt_verified     = models.BooleanField(default=False)
    receipt_verified_by  = models.ForeignKey(
        'accounts.CustomUser',
        on_delete    = models.PROTECT,
        related_name = 'procurement_receipt_verifications',
        null         = True,
        blank        = True,
    )
    receipt_verified_at  = models.DateTimeField(null=True, blank=True)
    receipt_variance_flagged = models.BooleanField(
        default   = False,
        help_text = 'True if receipt amount differs from approved budget by >5%.',
    )
    disbursement_method    = models.CharField(
        max_length = 20,
        choices    = [
            ('CASH',          'Cash'),
            ('CHEQUE',        'Cheque'),
            ('MOMO',          'Mobile Money'),
            ('BANK_TRANSFER', 'Bank Transfer'),
        ],
        blank = True,
    )
    disbursement_reference = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering            = ['-created_at']
        verbose_name        = 'Replenishment Order'
        verbose_name_plural = 'Replenishment Orders'
        indexes             = [
            models.Index(fields=['branch', 'status']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        return f"{self.order_number} — {self.branch.name} [{self.status}]"

    @property
    def is_editable(self):
        """Only DRAFT orders can have their line items modified."""
        return self.status == self.Status.DRAFT

    @property
    def can_submit_to_finance(self):
        return self.status == self.Status.DRAFT

    @property
    def can_approve(self):
        return self.status == self.Status.PENDING_FINANCE

    @property
    def can_dispatch(self):
        return self.status == self.Status.FINANCE_APPROVED

    @property
    def can_accept(self):
        return self.status == self.Status.DELIVERED


class ReplenishmentLineItem(AuditModel):
    """
    One line per consumable in a ReplenishmentOrder.

    requested_qty  — computed from EOW consumption data
    approved_qty   — may be adjusted by Finance if budget is tight
    delivered_qty  — actual quantity physically delivered
    accepted_qty   — quantity BM confirmed receipt of

    Discrepancy = delivered_qty != accepted_qty → triggers DeliveryDiscrepancy
    """

    order = models.ForeignKey(
        ReplenishmentOrder,
        on_delete    = models.CASCADE,
        related_name = 'line_items',
    )
    consumable = models.ForeignKey(
        'inventory.ConsumableItem',
        on_delete    = models.PROTECT,
        related_name = 'replenishment_lines',
    )
    requested_qty = models.DecimalField(
        max_digits     = 10,
        decimal_places = 2,
        help_text      = 'Quantity derived from EOW consumption.',
    )
    approved_qty = models.DecimalField(
        max_digits     = 10,
        decimal_places = 2,
        null           = True,
        blank          = True,
        help_text      = 'Quantity approved by Finance. Defaults to requested if not set.',
    )
    delivered_qty = models.DecimalField(
        max_digits     = 10,
        decimal_places = 2,
        null           = True,
        blank          = True,
        help_text      = 'Actual quantity delivered by Operations.',
    )
    accepted_qty = models.DecimalField(
        max_digits     = 10,
        decimal_places = 2,
        null           = True,
        blank          = True,
        help_text      = 'Quantity confirmed received by BM.',
    )
    unit_cost = models.DecimalField(
        max_digits     = 10,
        decimal_places = 2,
        default        = 0,
        help_text      = 'Estimated cost per unit at time of order generation.',
    )
    line_total = models.DecimalField(
        max_digits     = 12,
        decimal_places = 2,
        default        = 0,
        help_text      = 'requested_qty × unit_cost',
    )
    notes = models.TextField(blank=True)

    class Meta:
        ordering        = ['consumable__category', 'consumable__name']
        unique_together = [['order', 'consumable']]
        verbose_name        = 'Replenishment Line Item'
        verbose_name_plural = 'Replenishment Line Items'

    def __str__(self):
        return f"{self.order.order_number} — {self.consumable.name}"

    @property
    def effective_qty(self):
        """Approved qty takes precedence over requested if set."""
        return self.approved_qty if self.approved_qty is not None else self.requested_qty

    @property
    def has_discrepancy(self):
        if self.delivered_qty is None or self.accepted_qty is None:
            return False
        return self.delivered_qty != self.accepted_qty