# Generated by Django 6.0.3 on 2026-03-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_branch_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('pending_jobs', models.PositiveIntegerField(default=0)),
                ('in_progress_jobs', models.PositiveIntegerField(default=0)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('cancelled_jobs', models.PositiveIntegerField(default=0)),
                ('routed_out_jobs', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_job_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('unread_conversations', models.PositiveIntegerField(default=0)),
                ('resolved_conversations', models.PositiveIntegerField(default=0)),
                ('load_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='organization.branch')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['branch', 'date'], name='analytics_b_branch__fe29bb_idx')],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
