# Generated by Django 6.0.3 on 2026-04-02 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('finance', '0013_alter_cashierfloat_closing_denomination_breakdown'),
        ('organization', '0003_branch_closing_time_branch_getfund_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchsnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Branch Snapshot', 'verbose_name_plural': 'Branch Snapshots'},
        ),
        migrations.CreateModel(
            name='DailyRiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='0–100 weighted sum of flag severities. Capped at 100.')),
                ('flag_count_critical', models.PositiveSmallIntegerField(default=0)),
                ('flag_count_high', models.PositiveSmallIntegerField(default=0)),
                ('flag_count_medium', models.PositiveSmallIntegerField(default=0)),
                ('flag_count_low', models.PositiveSmallIntegerField(default=0)),
                ('generated_at', models.DateTimeField()),
                ('requires_rm_review', models.BooleanField(db_index=True, default=False, help_text='True if risk_score >= 40 or any CRITICAL flag exists.')),
                ('rm_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rm_notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_risk_reports', to='organization.branch')),
                ('daily_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_report', to='finance.dailysalessheet')),
                ('rm_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_daily_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Risk Report',
                'verbose_name_plural': 'Daily Risk Reports',
                'ordering': ['-date', '-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='DailyRiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('CASH_VARIANCE', 'Cash Variance'), ('PAYMENT_METHOD_SHIFT', 'Unusual Payment Method Distribution'), ('POST_CLOSING_JOB', 'Job Created After Sheet Close'), ('FLOAT_NOT_ACKNOWLEDGED', 'Float Not Acknowledged at Shift Start'), ('FLOAT_NOT_SIGNED_OFF', 'Float Not Signed Off at Shift End'), ('PAYMENT_OUTSIDE_SHIFT', 'Payment Confirmed Outside Shift Hours'), ('HIGH_SINGLE_PAYMENT', 'Unusually High Single Payment'), ('DUPLICATE_AMOUNT', 'Duplicate Payment Amount in Same Session'), ('SHORT_SESSION', 'Abnormally Short Session Duration'), ('CRITICAL_ACTION_SWITCH', 'Tab Switch During Critical Action'), ('NO_FLOAT_SET', 'No Float Set for Cashier'), ('CARRY_FORWARD_HIGH', 'High Carry-Forward Balance')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('description', models.TextField(help_text='Human-readable explanation. Must stand alone. Example: "Cash variance of GHS 45.00 detected. Expected GHS 1,250.00 (opening float GHS 100.00 + cash collected GHS 1,150.00), counted GHS 1,205.00."')),
                ('metadata', models.JSONField(default=dict, help_text='Raw numbers that produced this flag for programmatic use.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='analytics.dailyriskreport')),
            ],
            options={
                'verbose_name': 'Daily Risk Flag',
                'verbose_name_plural': 'Daily Risk Flags',
                'ordering': ['-severity', 'flag_type'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCloseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('overall_risk_score', models.PositiveSmallIntegerField(default=0, help_text='Weighted average of all weekly risk scores for the month.')),
                ('critical_days_count', models.PositiveSmallIntegerField(default=0, help_text='Days where DailyRiskReport.risk_level = CRITICAL')),
                ('high_risk_days_count', models.PositiveSmallIntegerField(default=0, help_text='Days where DailyRiskReport.risk_level = HIGH')),
                ('weeks_flagged_count', models.PositiveSmallIntegerField(default=0, help_text='Weeks where WeeklyRiskScore.finance_status = FLAGGED')),
                ('total_sessions', models.PositiveSmallIntegerField(default=0)),
                ('anomalous_sessions_count', models.PositiveSmallIntegerField(default=0)),
                ('total_critical_switches', models.PositiveSmallIntegerField(default=0, help_text='Total TAB_SWITCH_CRITICAL events across all sessions this month')),
                ('all_flags', models.JSONField(default=list, help_text='Flattened list of all DailyRiskFlags and WeeklyRiskFlags for the month. Finance reads this — one place to see every anomaly detected. Structure: [{type, severity, description, date, source}, ...]')),
                ('finance_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('finance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_status', models.CharField(choices=[('PENDING', 'Pending Finance Review'), ('CLEARED', 'Cleared by Finance'), ('FLAGGED', 'Flagged — Clarification Needed')], db_index=True, default='PENDING', max_length=10)),
                ('finance_notes', models.TextField(blank=True, help_text='Overall Finance reconciliation notes.')),
                ('clarification_requests', models.JSONField(default=list, help_text='Array of clarification requests between Finance and BM. Structure: [{  "id": "uuid",  "section": "revenue",  "question": "Cash variance of GHS 45 on March 24 — explain.",  "asked_by": "Finance Name",  "asked_at": "ISO datetime",  "response": "Till was short due to...",  "responded_by": "BM Name",  "responded_at": "ISO datetime",  "resolved": true}]')),
                ('generated_at', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='organization.branch')),
                ('finance_reviewer', models.ForeignKey(blank=True, help_text='Assigned Finance reviewer. Set on submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_finance_reviews', to=settings.AUTH_USER_MODEL)),
                ('monthly_close', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summary', to='finance.monthlyclose')),
            ],
            options={
                'verbose_name': 'Monthly Close Summary',
                'verbose_name_plural': 'Monthly Close Summaries',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('ATTENDANT', 'Attendant Portal'), ('CASHIER', 'Cashier Portal'), ('BRANCH_MANAGER', 'Branch Manager Portal'), ('REGIONAL_MANAGER', 'Regional Manager Portal'), ('FINANCE', 'Finance Portal'), ('BELT_MANAGER', 'Belt Manager Portal')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Null means session is still active', null=True)),
                ('last_seen_at', models.DateTimeField(help_text='Updated by frontend heartbeat every 60s')),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('active_duration_seconds', models.PositiveIntegerField(default=0)),
                ('idle_duration_seconds', models.PositiveIntegerField(default=0)),
                ('idle_count', models.PositiveSmallIntegerField(default=0, help_text='Number of idle periods > IDLE_THRESHOLD (default 5 min)')),
                ('critical_action_switches', models.PositiveSmallIntegerField(default=0, help_text='Tab/app switches detected during critical actions (payment confirmation, EOD sign-off). These are the high-signal events — not all tab switches.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_anomalous', models.BooleanField(db_index=True, default=False, help_text='Set by daily_risk_engine if session pattern is unusual')),
                ('anomaly_notes', models.TextField(blank=True, help_text='Human-readable explanation of what triggered is_anomalous')),
                ('branch', models.ForeignKey(blank=True, help_text='Null for HQ-level users (Finance, Belt Manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to='organization.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SESSION_START', 'Session Started'), ('SESSION_END', 'Session Ended'), ('SESSION_IDLE', 'Session Idle'), ('SESSION_TIMEOUT', 'Session Timed Out'), ('TAB_SWITCH_CRITICAL', 'Tab Switch During Critical Action'), ('SHEET_OPENED', 'Sheet Opened'), ('SHEET_CLOSED', 'Sheet Closed'), ('SHEET_AUTO_CLOSED', 'Sheet Auto-Closed'), ('FLOAT_SET', 'Float Set'), ('FLOAT_ACKNOWLEDGED', 'Float Acknowledged'), ('FLOAT_SIGNED_OFF', 'Float Signed Off'), ('FLOAT_VARIANCE', 'Float Variance Detected'), ('JOB_CREATED', 'Job Created'), ('JOB_MODIFIED', 'Job Modified'), ('JOB_VOIDED', 'Job Voided'), ('JOB_STATUS_CHANGED', 'Job Status Changed'), ('JOB_POST_CLOSING', 'Post-Closing Job Created'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_LATE', 'Late Payment'), ('PAYMENT_OUTSIDE_SHIFT', 'Payment Outside Shift Hours'), ('PETTY_CASH_RECORDED', 'Petty Cash Recorded'), ('CREDIT_ISSUED', 'Credit Issued'), ('CREDIT_SETTLED', 'Credit Settled'), ('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PIN_USED', 'PIN Used'), ('MONTHLY_SUBMITTED', 'Monthly Close Submitted'), ('MONTHLY_FINANCE_REVIEW', 'Monthly Close Finance Review'), ('MONTHLY_CLARIFICATION', 'Monthly Close Clarification Requested'), ('MONTHLY_RESUBMITTED', 'Monthly Close Resubmitted'), ('MONTHLY_ENDORSED', 'Monthly Close Endorsed'), ('MONTHLY_REJECTED', 'Monthly Close Rejected'), ('MONTHLY_LOCKED', 'Monthly Close Locked')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10)),
                ('entity_type', models.CharField(blank=True, help_text="Model class name e.g. 'Job', 'CashierFloat', 'Receipt'", max_length=50)),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='PK of the affected record', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Self-contained context captured at event time. Must be understandable without querying related models. Example for PAYMENT_CONFIRMED: {"amount": 150.00, "method": "CASH", "job_number": "WLB-0042", "tendered": 200.00, "change": 50.00, "queue_wait_minutes": 3}')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Explicit timestamp — not auto_now_add. Allows backfill of historical events.')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='0–100. Assigned by daily_risk_engine during EOD analysis. 0 at creation time for most events.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organization.branch')),
                ('user', models.ForeignKey(blank=True, help_text='Null for system-generated events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='The portal session during which this event occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='0–100. Weighted average of daily scores + week-level flags.')),
                ('highest_daily_risk', models.PositiveSmallIntegerField(default=0)),
                ('average_daily_risk', models.PositiveSmallIntegerField(default=0)),
                ('critical_days_count', models.PositiveSmallIntegerField(default=0)),
                ('high_days_count', models.PositiveSmallIntegerField(default=0)),
                ('requires_finance_review', models.BooleanField(db_index=True, default=False, help_text='True if risk_score >= 50 or any CRITICAL flag.')),
                ('finance_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('finance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CLEARED', 'Cleared by Finance'), ('FLAGGED', 'Flagged — Needs Attention')], db_index=True, default='PENDING', max_length=10)),
                ('finance_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_risk_scores', to='organization.branch')),
                ('finance_reviewer', models.ForeignKey(blank=True, help_text='Assigned Finance reviewer (HQ level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_finance_reviews', to=settings.AUTH_USER_MODEL)),
                ('weekly_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='finance.weeklyreport')),
            ],
            options={
                'verbose_name': 'Weekly Risk Score',
                'verbose_name_plural': 'Weekly Risk Scores',
                'ordering': ['-year', '-week_number', '-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('REVENUE_ANOMALY', 'Revenue Anomaly vs Rolling Average'), ('HIGH_CASH_PROPORTION', 'Cash > 80% of Weekly Revenue'), ('COMPLETION_RATE_DROP', 'Completion Rate Below Branch Average'), ('DAILY_OUTLIER', 'Single Day > 3 Standard Deviations from Mean'), ('CARRY_FORWARD_HIGH', 'High Carry-Forward Balance'), ('REVENUE_VS_PRIOR', 'Revenue Variance vs Same Week Last Month'), ('MULTIPLE_HIGH_RISK', 'Multiple High-Risk Days in One Week'), ('SESSION_PATTERN', 'Abnormal Session Patterns Across Week')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='analytics.weeklyriskscore')),
            ],
            options={
                'verbose_name': 'Weekly Risk Flag',
                'verbose_name_plural': 'Weekly Risk Flags',
                'ordering': ['-severity', 'flag_type'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyriskreport',
            index=models.Index(fields=['branch', 'date'], name='analytics_d_branch__964191_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyriskreport',
            index=models.Index(fields=['risk_score'], name='analytics_d_risk_sc_824985_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyriskreport',
            index=models.Index(fields=['requires_rm_review', 'date'], name='analytics_d_require_1e7797_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclosesummary',
            index=models.Index(fields=['branch', 'year', 'month'], name='analytics_m_branch__48c3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclosesummary',
            index=models.Index(fields=['finance_status'], name='analytics_m_finance_8d5287_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyclosesummary',
            index=models.Index(fields=['overall_risk_score'], name='analytics_m_overall_47ad50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyclosesummary',
            unique_together={('monthly_close',)},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_u_user_id_c1ab02_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['branch', 'started_at'], name='analytics_u_branch__423a46_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['portal', 'started_at'], name='analytics_u_portal_73a931_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_anomalous', 'started_at'], name='analytics_u_is_anom_756b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['branch', 'timestamp'], name='analytics_a_branch__5c8c60_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_a4aac9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_a_event_t_d91e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['severity', 'timestamp'], name='analytics_a_severit_0c04e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='analytics_a_entity__22842a_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyriskscore',
            index=models.Index(fields=['branch', 'year', 'week_number'], name='analytics_w_branch__480423_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyriskscore',
            index=models.Index(fields=['risk_score'], name='analytics_w_risk_sc_62cb02_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyriskscore',
            index=models.Index(fields=['requires_finance_review', 'finance_status'], name='analytics_w_require_1f3944_idx'),
        ),
    ]
