# Generated by Django 6.0.3 on 2026-06-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_branchsnapshot_options_dailyriskreport_and_more'),
        ('finance', '0021_add_hourly_sheet_snapshot'),
        ('organization', '0004_add_branch_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlySheetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weekday', models.PositiveSmallIntegerField(db_index=True, help_text='0=Monday, 6=Sunday — denormalised for fast filtering')),
                ('week_of_month', models.PositiveSmallIntegerField(help_text='1–5 — which week of the month this date falls in')),
                ('hour', models.PositiveSmallIntegerField(help_text='Hour slot 7–19 (7am to 7pm)')),
                ('job_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_job_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weather_condition', models.CharField(blank=True, help_text='clear | cloudy | light_rain | heavy_rain | harmattan', max_length=30)),
                ('precipitation_mm', models.DecimalField(decimal_places=2, default=0, help_text='Actual precipitation for this hour in mm', max_digits=6)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_snapshots', to='organization.branch')),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_snapshots', to='finance.dailysalessheet')),
            ],
            options={
                'verbose_name': 'Hourly Sheet Snapshot',
                'verbose_name_plural': 'Hourly Sheet Snapshots',
                'ordering': ['date', 'hour'],
                'indexes': [models.Index(fields=['branch', 'weekday', 'hour'], name='analytics_h_branch__6dfe5b_idx'), models.Index(fields=['branch', 'date'], name='analytics_h_branch__42424b_idx')],
                'unique_together': {('daily_sheet', 'hour')},
            },
        ),
    ]
