# Generated by Django 6.0.3 on 2026-10-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0009_customerprofile_wallet_balance_and_more'),
        ('jobs', '0031_jobfile_pdf_images'),
        ('organization', '0004_add_branch_coordinates'),
    ]

    operations = [
                # The order number comes from a sequence rather than from the
        # highest number so far: two strangers can click in the same
        # millisecond, and reading the maximum would hand both the same
        # number. Created here so the model's save only reads.
        migrations.RunSQL(
            sql='CREATE SEQUENCE IF NOT EXISTS storefront_order_seq AS BIGINT START WITH 1;',
            reverse_sql='DROP SEQUENCE IF EXISTS storefront_order_seq;',
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, help_text='Hashed. Set when the lead chooses to keep their history.', max_length=128)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('last_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(blank=True, help_text='Set on the visit that turns this lead into a customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='customers.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Being built'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('CONVERTED', 'Converted to a job'), ('ABANDONED', 'Abandoned'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fulfilment', models.CharField(choices=[('COLLECTION', 'Collection'), ('DELIVERY', 'Delivery')], default='COLLECTION', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('promised_for', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_orders', to='organization.branch')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_order', to='jobs.job')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='storefront.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='storefront__status_23fcaa_idx')],
            },
        ),
    ]
