# Generated by Django 6.0.3 on 2026-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64, unique=True),
        ),
    ]
