# Generated by Django 6.0.3 on 2026-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_onlineorder_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='pin',
        ),
        migrations.AddField(
            model_name='lead',
            name='code',
            field=models.CharField(blank=True, help_text='Hashed. Set when the customer chooses to keep their history.', max_length=128),
        ),
        migrations.AddField(
            model_name='lead',
            name='code_discount_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='full_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
