# Generated by Django 6.0.3 on 2026-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_remove_lead_pin_lead_code_lead_code_discount_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='net_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
