# Generated by Django 6.0.3 on 2026-10-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_onlineorder_net_received_onlineorder_payment_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=50)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='storefront.onlineorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
