# Generated by Django 6.0.3 on 2026-10-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_paystackevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='storefront/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('metadata_state', models.CharField(blank=True, max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dpi', models.PositiveIntegerField(blank=True, null=True)),
                ('colour_mode', models.CharField(blank=True, max_length=20)),
                ('pdf_images', models.JSONField(blank=True, default=list)),
                ('verdict', models.CharField(blank=True, max_length=10)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('warning_accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storefront.onlineorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
