# Generated by Django 6.0.3 on 2026-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_orderfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='line_id',
            field=models.CharField(blank=True, db_index=True, help_text="Which line of the order this artwork belongs to. An order can hold a banner, flyers and programmes at once, and the banner's file is not the flyer's — so a file belongs to a line rather than to the order as a whole.", max_length=36),
        ),
    ]
