# Generated by Django 6.0.3 on 2026-10-10 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_stagedupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('result', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='storefront.onlineorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
