# Generated by Django 6.0.3 on 2026-07-07 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ALERT', 'Alert'), ('REMINDER', 'Reminder')], db_index=True, default='ALERT', help_text='ALERT = event-driven (existing behavior). REMINDER = time/schedule-driven.', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Used with get_or_create to prevent duplicate reminder creation across task runs, e.g. "shift_ending-{user_id}-{date}-{bucket}". Blank for one-off ALERT notifications.', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='display_mode',
            field=models.CharField(choices=[('PASSIVE', 'Passive (bell only)'), ('INTERRUPTIVE', 'Interruptive (modal + bell)')], db_index=True, default='PASSIVE', help_text='PASSIVE = bell only. INTERRUPTIVE = full-screen modal until dismissed, plus bell.', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_pin',
            field=models.BooleanField(default=False, help_text='True for personal-note reminders — message stays generic, real content is never exposed here, only accessible via the PIN-gated personal_notes endpoint.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('job_created', 'Job Created'), ('job_status_changed', 'Job Status Changed'), ('job_routed', 'Job Routed'), ('message_received', 'Message Received'), ('conversation_assigned', 'Conversation Assigned'), ('employee_created', 'Employee Created'), ('shift_ending', 'Shift Ending Soon'), ('task_checkpoint', 'Personal Task Reminder'), ('system', 'System')], db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'display_mode', 'is_read'], name='notificatio_recipie_936957_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['dedupe_key'], name='notificatio_dedupe__f63021_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='unique_nonblank_dedupe_key'),
        ),
    ]
